package pullup.wallet;

import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.pc.*;

public class historiales_subs_0 {


public static RemoteObject  _activity_create(RemoteObject _firsttime) throws Exception{
try {
		Debug.PushSubsStack("Activity_Create (historiales) ","historiales",10,historiales.mostCurrent.activityBA,historiales.mostCurrent,32);
if (RapidSub.canDelegate("activity_create")) { return pullup.wallet.historiales.remoteMe.runUserSub(false, "historiales","activity_create", _firsttime);}
RemoteObject _lblseccion = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _top = RemoteObject.createImmutable(0);
int _id = 0;
RemoteObject _datoshistorial = RemoteObject.declareNull("pullup.wallet.historiales._historial");
RemoteObject _lblmensaje = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
Debug.locals.put("FirstTime", _firsttime);
 BA.debugLineNum = 32;BA.debugLine="Sub Activity_Create(FirstTime As Boolean)";
Debug.ShouldStop(-2147483648);
 BA.debugLineNum = 34;BA.debugLine="Activity.LoadLayout(\"LDeslizable\")";
Debug.ShouldStop(2);
historiales.mostCurrent._activity.runMethodAndSync(false,"LoadLayout",(Object)(RemoteObject.createImmutable("LDeslizable")),historiales.mostCurrent.activityBA);
 BA.debugLineNum = 35;BA.debugLine="Activity.Color = Colors.ARGB(255, 233, 236, 239)";
Debug.ShouldStop(4);
historiales.mostCurrent._activity.runVoidMethod ("setColor",historiales.mostCurrent.__c.getField(false,"Colors").runMethod(true,"ARGB",(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 233)),(Object)(BA.numberCast(int.class, 236)),(Object)(BA.numberCast(int.class, 239))));
 BA.debugLineNum = 36;BA.debugLine="alturaDispositivo = Main.alturaDispositivo";
Debug.ShouldStop(8);
historiales._alturadispositivo = historiales.mostCurrent._main._alturadispositivo /*RemoteObject*/ ;
 BA.debugLineNum = 37;BA.debugLine="anchoDispositivo = Main.anchoDispositivo";
Debug.ShouldStop(16);
historiales._anchodispositivo = historiales.mostCurrent._main._anchodispositivo /*RemoteObject*/ ;
 BA.debugLineNum = 38;BA.debugLine="sql = Starter.sql";
Debug.ShouldStop(32);
historiales._sql = historiales.mostCurrent._starter._sql /*RemoteObject*/ ;
 BA.debugLineNum = 39;BA.debugLine="bmpTest.InitializeMutable(1dip, 1dip)";
Debug.ShouldStop(64);
historiales.mostCurrent._bmptest.runVoidMethod ("InitializeMutable",(Object)(historiales.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 1)))),(Object)(historiales.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 1)))));
 BA.debugLineNum = 40;BA.debugLine="cvsTest.Initialize2(bmpTest)";
Debug.ShouldStop(128);
historiales.mostCurrent._cvstest.runVoidMethod ("Initialize2",(Object)((historiales.mostCurrent._bmptest.getObject())));
 BA.debugLineNum = 43;BA.debugLine="pnlNavInferior.Height = alturaDispositivo * 0.08";
Debug.ShouldStop(1024);
historiales.mostCurrent._pnlnavinferior.runMethod(true,"setHeight",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {historiales._alturadispositivo,RemoteObject.createImmutable(0.08)}, "*",0, 0)));
 BA.debugLineNum = 44;BA.debugLine="pnlNavInferior.Width = anchoDispositivo";
Debug.ShouldStop(2048);
historiales.mostCurrent._pnlnavinferior.runMethod(true,"setWidth",historiales._anchodispositivo);
 BA.debugLineNum = 45;BA.debugLine="pnlNavInferior.Left = 0";
Debug.ShouldStop(4096);
historiales.mostCurrent._pnlnavinferior.runMethod(true,"setLeft",BA.numberCast(int.class, 0));
 BA.debugLineNum = 46;BA.debugLine="pnlNavInferior.Top = alturaDispositivo - pnlNavIn";
Debug.ShouldStop(8192);
historiales.mostCurrent._pnlnavinferior.runMethod(true,"setTop",RemoteObject.solve(new RemoteObject[] {historiales._alturadispositivo,historiales.mostCurrent._pnlnavinferior.runMethod(true,"getHeight")}, "-",1, 1));
 BA.debugLineNum = 49;BA.debugLine="btnMenu.Width = anchoDispositivo * 0.15";
Debug.ShouldStop(65536);
historiales.mostCurrent._btnmenu.runMethod(true,"setWidth",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {historiales._anchodispositivo,RemoteObject.createImmutable(0.15)}, "*",0, 0)));
 BA.debugLineNum = 50;BA.debugLine="btnMenu.Height = btnMenu.Width";
Debug.ShouldStop(131072);
historiales.mostCurrent._btnmenu.runMethod(true,"setHeight",historiales.mostCurrent._btnmenu.runMethod(true,"getWidth"));
 BA.debugLineNum = 51;BA.debugLine="btnMenu.Top = pnlNavInferior.Top - btnMenu.Height";
Debug.ShouldStop(262144);
historiales.mostCurrent._btnmenu.runMethod(true,"setTop",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {historiales.mostCurrent._pnlnavinferior.runMethod(true,"getTop"),historiales.mostCurrent._btnmenu.runMethod(true,"getHeight"),RemoteObject.createImmutable(2)}, "-/",1, 0)));
 BA.debugLineNum = 52;BA.debugLine="btnMenu.Left = (anchoDispositivo - btnMenu.Width)";
Debug.ShouldStop(524288);
historiales.mostCurrent._btnmenu.runMethod(true,"setLeft",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {(RemoteObject.solve(new RemoteObject[] {historiales._anchodispositivo,historiales.mostCurrent._btnmenu.runMethod(true,"getWidth")}, "-",1, 1)),RemoteObject.createImmutable(2)}, "/",0, 0)));
 BA.debugLineNum = 54;BA.debugLine="lblContornoBoton.Width = anchoDispositivo * 0.17";
Debug.ShouldStop(2097152);
historiales.mostCurrent._lblcontornoboton.runMethod(true,"setWidth",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {historiales._anchodispositivo,RemoteObject.createImmutable(0.17)}, "*",0, 0)));
 BA.debugLineNum = 55;BA.debugLine="lblContornoBoton.Height = lblContornoBoton.Width";
Debug.ShouldStop(4194304);
historiales.mostCurrent._lblcontornoboton.runMethod(true,"setHeight",historiales.mostCurrent._lblcontornoboton.runMethod(true,"getWidth"));
 BA.debugLineNum = 56;BA.debugLine="lblContornoBoton.Left = (anchoDispositivo - lblCo";
Debug.ShouldStop(8388608);
historiales.mostCurrent._lblcontornoboton.runMethod(true,"setLeft",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {(RemoteObject.solve(new RemoteObject[] {historiales._anchodispositivo,historiales.mostCurrent._lblcontornoboton.runMethod(true,"getWidth")}, "-",1, 1)),RemoteObject.createImmutable(2)}, "/",0, 0)));
 BA.debugLineNum = 57;BA.debugLine="lblContornoBoton.Top = pnlNavInferior.Top - lblCo";
Debug.ShouldStop(16777216);
historiales.mostCurrent._lblcontornoboton.runMethod(true,"setTop",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {historiales.mostCurrent._pnlnavinferior.runMethod(true,"getTop"),historiales.mostCurrent._lblcontornoboton.runMethod(true,"getHeight"),RemoteObject.createImmutable(2)}, "-/",1, 0)));
 BA.debugLineNum = 61;BA.debugLine="svPantalla.Height = pnlNavInferior.Top";
Debug.ShouldStop(268435456);
historiales.mostCurrent._svpantalla.runMethod(true,"setHeight",historiales.mostCurrent._pnlnavinferior.runMethod(true,"getTop"));
 BA.debugLineNum = 62;BA.debugLine="svPantalla.Panel.LoadLayout(\"LPantallaDeslizable\"";
Debug.ShouldStop(536870912);
historiales.mostCurrent._svpantalla.runMethod(false,"getPanel").runMethodAndSync(false,"LoadLayout",(Object)(RemoteObject.createImmutable("LPantallaDeslizable")),historiales.mostCurrent.activityBA);
 BA.debugLineNum = 63;BA.debugLine="svPantalla.Width = anchoDispositivo * 1.5";
Debug.ShouldStop(1073741824);
historiales.mostCurrent._svpantalla.runMethod(true,"setWidth",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {historiales._anchodispositivo,RemoteObject.createImmutable(1.5)}, "*",0, 0)));
 BA.debugLineNum = 64;BA.debugLine="pnlDeslizable.Width = svPantalla.Width";
Debug.ShouldStop(-2147483648);
historiales.mostCurrent._pnldeslizable.runMethod(true,"setWidth",historiales.mostCurrent._svpantalla.runMethod(true,"getWidth"));
 BA.debugLineNum = 70;BA.debugLine="Dim lblSeccion As Label";
Debug.ShouldStop(32);
_lblseccion = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("lblSeccion", _lblseccion);
 BA.debugLineNum = 71;BA.debugLine="lblSeccion.Initialize(\"lblSeccion\")";
Debug.ShouldStop(64);
_lblseccion.runVoidMethod ("Initialize",historiales.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("lblSeccion")));
 BA.debugLineNum = 72;BA.debugLine="lblSeccion.Text = \"Historiales\"";
Debug.ShouldStop(128);
_lblseccion.runMethod(true,"setText",BA.ObjectToCharSequence("Historiales"));
 BA.debugLineNum = 73;BA.debugLine="lblSeccion.TextSize = 20";
Debug.ShouldStop(256);
_lblseccion.runMethod(true,"setTextSize",BA.numberCast(float.class, 20));
 BA.debugLineNum = 74;BA.debugLine="lblSeccion.TextColor = Colors.Black";
Debug.ShouldStop(512);
_lblseccion.runMethod(true,"setTextColor",historiales.mostCurrent.__c.getField(false,"Colors").getField(true,"Black"));
 BA.debugLineNum = 75;BA.debugLine="lblSeccion.Height = 30dip";
Debug.ShouldStop(1024);
_lblseccion.runMethod(true,"setHeight",historiales.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 30))));
 BA.debugLineNum = 76;BA.debugLine="lblSeccion.Width = anchoDispositivo * 0.9";
Debug.ShouldStop(2048);
_lblseccion.runMethod(true,"setWidth",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {historiales._anchodispositivo,RemoteObject.createImmutable(0.9)}, "*",0, 0)));
 BA.debugLineNum = 77;BA.debugLine="lblSeccion.Top = 30dip";
Debug.ShouldStop(4096);
_lblseccion.runMethod(true,"setTop",historiales.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 30))));
 BA.debugLineNum = 78;BA.debugLine="lblSeccion.Left = (anchoDispositivo - lblSeccion.";
Debug.ShouldStop(8192);
_lblseccion.runMethod(true,"setLeft",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {(RemoteObject.solve(new RemoteObject[] {historiales._anchodispositivo,_lblseccion.runMethod(true,"getWidth")}, "-",1, 1)),RemoteObject.createImmutable(2)}, "/",0, 0)));
 BA.debugLineNum = 79;BA.debugLine="pnlDeslizable.AddView(lblSeccion, lblSeccion.Left";
Debug.ShouldStop(16384);
historiales.mostCurrent._pnldeslizable.runVoidMethod ("AddView",(Object)((_lblseccion.getObject())),(Object)(_lblseccion.runMethod(true,"getLeft")),(Object)(_lblseccion.runMethod(true,"getTop")),(Object)(_lblseccion.runMethod(true,"getWidth")),(Object)(_lblseccion.runMethod(true,"getHeight")));
 BA.debugLineNum = 84;BA.debugLine="Dim top As Int";
Debug.ShouldStop(524288);
_top = RemoteObject.createImmutable(0);Debug.locals.put("top", _top);
 BA.debugLineNum = 85;BA.debugLine="top = lblSeccion.Top + lblSeccion.Height + 30dip";
Debug.ShouldStop(1048576);
_top = RemoteObject.solve(new RemoteObject[] {_lblseccion.runMethod(true,"getTop"),_lblseccion.runMethod(true,"getHeight"),historiales.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 30)))}, "++",2, 1);Debug.locals.put("top", _top);
 BA.debugLineNum = 88;BA.debugLine="cur = sql.ExecQuery(\"SELECT * FROM historial_bala";
Debug.ShouldStop(8388608);
historiales.mostCurrent._cur = RemoteObject.declareNull("anywheresoftware.b4a.AbsObjectWrapper").runMethod(false, "ConvertToWrapper", RemoteObject.createNew("anywheresoftware.b4a.sql.SQL.CursorWrapper"), historiales._sql.runMethod(false,"ExecQuery",(Object)(RemoteObject.createImmutable("SELECT * FROM historial_balance ORDER BY rowid ASC"))));
 BA.debugLineNum = 89;BA.debugLine="nRegistros = cur.RowCount";
Debug.ShouldStop(16777216);
historiales._nregistros = historiales.mostCurrent._cur.runMethod(true,"getRowCount");
 BA.debugLineNum = 93;BA.debugLine="If nRegistros > 0 Then";
Debug.ShouldStop(268435456);
if (RemoteObject.solveBoolean(">",historiales._nregistros,BA.numberCast(double.class, 0))) { 
 BA.debugLineNum = 95;BA.debugLine="For id = 0 To nRegistros - 1";
Debug.ShouldStop(1073741824);
{
final int step39 = 1;
final int limit39 = RemoteObject.solve(new RemoteObject[] {historiales._nregistros,RemoteObject.createImmutable(1)}, "-",1, 1).<Integer>get().intValue();
_id = 0 ;
for (;(step39 > 0 && _id <= limit39) || (step39 < 0 && _id >= limit39) ;_id = ((int)(0 + _id + step39))  ) {
Debug.locals.put("id", _id);
 BA.debugLineNum = 96;BA.debugLine="cur.Position = id";
Debug.ShouldStop(-2147483648);
historiales.mostCurrent._cur.runMethod(true,"setPosition",BA.numberCast(int.class, _id));
 BA.debugLineNum = 98;BA.debugLine="Dim datosHistorial As Historial";
Debug.ShouldStop(2);
_datoshistorial = RemoteObject.createNew ("pullup.wallet.historiales._historial");Debug.locals.put("datosHistorial", _datoshistorial);
 BA.debugLineNum = 99;BA.debugLine="datosHistorial.rowid = cur.GetInt(\"id_historial";
Debug.ShouldStop(4);
_datoshistorial.setField ("rowid" /*RemoteObject*/ ,historiales.mostCurrent._cur.runMethod(true,"GetInt",(Object)(RemoteObject.createImmutable("id_historial"))));
 BA.debugLineNum = 100;BA.debugLine="datosHistorial.sumaIngresos = cur.GetInt(\"suma_";
Debug.ShouldStop(8);
_datoshistorial.setField ("sumaIngresos" /*RemoteObject*/ ,historiales.mostCurrent._cur.runMethod(true,"GetInt",(Object)(RemoteObject.createImmutable("suma_ingresos"))));
 BA.debugLineNum = 101;BA.debugLine="datosHistorial.sumaEgresos = cur.GetInt(\"suma_e";
Debug.ShouldStop(16);
_datoshistorial.setField ("sumaEgresos" /*RemoteObject*/ ,historiales.mostCurrent._cur.runMethod(true,"GetInt",(Object)(RemoteObject.createImmutable("suma_egresos"))));
 BA.debugLineNum = 102;BA.debugLine="datosHistorial.balance = cur.GetInt(\"balance\")";
Debug.ShouldStop(32);
_datoshistorial.setField ("balance" /*RemoteObject*/ ,historiales.mostCurrent._cur.runMethod(true,"GetInt",(Object)(RemoteObject.createImmutable("balance"))));
 BA.debugLineNum = 103;BA.debugLine="datosHistorial.fechaHistorial = cur.GetString(\"";
Debug.ShouldStop(64);
_datoshistorial.setField ("fechaHistorial" /*RemoteObject*/ ,historiales.mostCurrent._cur.runMethod(true,"GetString",(Object)(RemoteObject.createImmutable("fecha_historial"))));
 BA.debugLineNum = 105;BA.debugLine="creaObjetoLista(top, datosHistorial)";
Debug.ShouldStop(256);
_creaobjetolista(_top,_datoshistorial);
 BA.debugLineNum = 107;BA.debugLine="top = top + alturaDispositivo * 0.2 + 60";
Debug.ShouldStop(1024);
_top = BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {_top,historiales._alturadispositivo,RemoteObject.createImmutable(0.2),RemoteObject.createImmutable(60)}, "+*+",2, 0));Debug.locals.put("top", _top);
 }
}Debug.locals.put("id", _id);
;
 }else {
 BA.debugLineNum = 111;BA.debugLine="Dim lblMensaje As Label";
Debug.ShouldStop(16384);
_lblmensaje = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("lblMensaje", _lblmensaje);
 BA.debugLineNum = 112;BA.debugLine="lblMensaje.Initialize(\"lblMensaje\")";
Debug.ShouldStop(32768);
_lblmensaje.runVoidMethod ("Initialize",historiales.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("lblMensaje")));
 BA.debugLineNum = 113;BA.debugLine="lblMensaje.Height = alturaDispositivo * 0.2";
Debug.ShouldStop(65536);
_lblmensaje.runMethod(true,"setHeight",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {historiales._alturadispositivo,RemoteObject.createImmutable(0.2)}, "*",0, 0)));
 BA.debugLineNum = 114;BA.debugLine="lblMensaje.Width = anchoDispositivo * 0.9";
Debug.ShouldStop(131072);
_lblmensaje.runMethod(true,"setWidth",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {historiales._anchodispositivo,RemoteObject.createImmutable(0.9)}, "*",0, 0)));
 BA.debugLineNum = 115;BA.debugLine="lblMensaje.Top = (alturaDispositivo - lblMensaje";
Debug.ShouldStop(262144);
_lblmensaje.runMethod(true,"setTop",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {(RemoteObject.solve(new RemoteObject[] {historiales._alturadispositivo,_lblmensaje.runMethod(true,"getHeight")}, "-",1, 1)),RemoteObject.createImmutable(2)}, "/",0, 0)));
 BA.debugLineNum = 116;BA.debugLine="lblMensaje.Left = (anchoDispositivo - lblMensaje";
Debug.ShouldStop(524288);
_lblmensaje.runMethod(true,"setLeft",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {(RemoteObject.solve(new RemoteObject[] {historiales._anchodispositivo,_lblmensaje.runMethod(true,"getWidth")}, "-",1, 1)),RemoteObject.createImmutable(2)}, "/",0, 0)));
 BA.debugLineNum = 117;BA.debugLine="lblMensaje.Text = cs.Initialize.Color(Colors.Bla";
Debug.ShouldStop(1048576);
_lblmensaje.runMethod(true,"setText",BA.ObjectToCharSequence(historiales.mostCurrent._cs.runMethod(false,"Initialize").runMethod(false,"Color",(Object)(historiales.mostCurrent.__c.getField(false,"Colors").getField(true,"Black"))).runMethod(false,"Alignment",(Object)(BA.getEnumFromString(BA.getDeviceClass("android.text.Layout.Alignment"),RemoteObject.createImmutable("ALIGN_CENTER")))).runMethod(false,"Typeface",(Object)(historiales.mostCurrent.__c.getField(false,"Typeface").runMethod(false,"getMATERIALICONS"))).runMethod(false,"Size",(Object)(BA.numberCast(int.class, 50))).runMethod(false,"Append",(Object)(BA.ObjectToCharSequence(RemoteObject.concat(historiales.mostCurrent.__c.runMethod(true,"Chr",(Object)(BA.numberCast(int.class, 0xe89c))),historiales.mostCurrent.__c.getField(true,"CRLF"))))).runMethod(false,"Typeface",(Object)(historiales.mostCurrent.__c.getField(false,"Typeface").getField(false,"DEFAULT"))).runMethod(false,"Size",(Object)(BA.numberCast(int.class, 18))).runMethod(false,"Append",(Object)(BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable("Está muy vacío aquí adentro."),historiales.mostCurrent.__c.getField(true,"CRLF"))))).runMethod(false,"Append",(Object)(BA.ObjectToCharSequence(RemoteObject.createImmutable("Genera tu historial si lo crees necesario.")))).runMethod(false,"PopAll").getObject()));
 BA.debugLineNum = 118;BA.debugLine="Activity.AddView(lblMensaje, lblMensaje.Left, lb";
Debug.ShouldStop(2097152);
historiales.mostCurrent._activity.runVoidMethod ("AddView",(Object)((_lblmensaje.getObject())),(Object)(_lblmensaje.runMethod(true,"getLeft")),(Object)(_lblmensaje.runMethod(true,"getTop")),(Object)(_lblmensaje.runMethod(true,"getWidth")),(Object)(_lblmensaje.runMethod(true,"getHeight")));
 };
 BA.debugLineNum = 121;BA.debugLine="svPantalla.Panel.Height = top + 100";
Debug.ShouldStop(16777216);
historiales.mostCurrent._svpantalla.runMethod(false,"getPanel").runMethod(true,"setHeight",RemoteObject.solve(new RemoteObject[] {_top,RemoteObject.createImmutable(100)}, "+",1, 1));
 BA.debugLineNum = 122;BA.debugLine="End Sub";
Debug.ShouldStop(33554432);
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _activity_pause(RemoteObject _userclosed) throws Exception{
try {
		Debug.PushSubsStack("Activity_Pause (historiales) ","historiales",10,historiales.mostCurrent.activityBA,historiales.mostCurrent,128);
if (RapidSub.canDelegate("activity_pause")) { return pullup.wallet.historiales.remoteMe.runUserSub(false, "historiales","activity_pause", _userclosed);}
Debug.locals.put("UserClosed", _userclosed);
 BA.debugLineNum = 128;BA.debugLine="Sub Activity_Pause (UserClosed As Boolean)";
Debug.ShouldStop(-2147483648);
 BA.debugLineNum = 130;BA.debugLine="End Sub";
Debug.ShouldStop(2);
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _activity_resume() throws Exception{
try {
		Debug.PushSubsStack("Activity_Resume (historiales) ","historiales",10,historiales.mostCurrent.activityBA,historiales.mostCurrent,124);
if (RapidSub.canDelegate("activity_resume")) { return pullup.wallet.historiales.remoteMe.runUserSub(false, "historiales","activity_resume");}
 BA.debugLineNum = 124;BA.debugLine="Sub Activity_Resume";
Debug.ShouldStop(134217728);
 BA.debugLineNum = 126;BA.debugLine="End Sub";
Debug.ShouldStop(536870912);
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _btnmenu_click() throws Exception{
try {
		Debug.PushSubsStack("btnMenu_Click (historiales) ","historiales",10,historiales.mostCurrent.activityBA,historiales.mostCurrent,132);
if (RapidSub.canDelegate("btnmenu_click")) { return pullup.wallet.historiales.remoteMe.runUserSub(false, "historiales","btnmenu_click");}
 BA.debugLineNum = 132;BA.debugLine="Private Sub btnMenu_Click";
Debug.ShouldStop(8);
 BA.debugLineNum = 133;BA.debugLine="Activity.Finish";
Debug.ShouldStop(16);
historiales.mostCurrent._activity.runVoidMethod ("Finish");
 BA.debugLineNum = 134;BA.debugLine="End Sub";
Debug.ShouldStop(32);
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _creaobjetolista(RemoteObject _top,RemoteObject _datos) throws Exception{
try {
		Debug.PushSubsStack("creaObjetoLista (historiales) ","historiales",10,historiales.mostCurrent.activityBA,historiales.mostCurrent,137);
if (RapidSub.canDelegate("creaobjetolista")) { return pullup.wallet.historiales.remoteMe.runUserSub(false, "historiales","creaobjetolista", _top, _datos);}
RemoteObject _pnlhistorial = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
RemoteObject _lblbalance = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _lblingresos = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _lblegresos = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _lblfechahistorial = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _lbleliminar = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _lbliconoingresos = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _lbliconoegresos = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _cd = RemoteObject.declareNull("anywheresoftware.b4a.objects.drawable.ColorDrawable");
RemoteObject _referencia = RemoteObject.declareNull("pullup.wallet.historiales._indicehistorial");
Debug.locals.put("top", _top);
Debug.locals.put("datos", _datos);
 BA.debugLineNum = 137;BA.debugLine="Sub creaObjetoLista(top As Int, datos As Historial";
Debug.ShouldStop(256);
 BA.debugLineNum = 138;BA.debugLine="Dim pnlHistorial As Panel";
Debug.ShouldStop(512);
_pnlhistorial = RemoteObject.createNew ("anywheresoftware.b4a.objects.PanelWrapper");Debug.locals.put("pnlHistorial", _pnlhistorial);
 BA.debugLineNum = 139;BA.debugLine="Dim lblBalance As Label";
Debug.ShouldStop(1024);
_lblbalance = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("lblBalance", _lblbalance);
 BA.debugLineNum = 140;BA.debugLine="Dim lblIngresos As Label";
Debug.ShouldStop(2048);
_lblingresos = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("lblIngresos", _lblingresos);
 BA.debugLineNum = 141;BA.debugLine="Dim lblEgresos As Label";
Debug.ShouldStop(4096);
_lblegresos = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("lblEgresos", _lblegresos);
 BA.debugLineNum = 142;BA.debugLine="Dim lblFechaHistorial As Label";
Debug.ShouldStop(8192);
_lblfechahistorial = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("lblFechaHistorial", _lblfechahistorial);
 BA.debugLineNum = 143;BA.debugLine="Dim lblEliminar As Label";
Debug.ShouldStop(16384);
_lbleliminar = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("lblEliminar", _lbleliminar);
 BA.debugLineNum = 144;BA.debugLine="Dim lblIconoIngresos As Label";
Debug.ShouldStop(32768);
_lbliconoingresos = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("lblIconoIngresos", _lbliconoingresos);
 BA.debugLineNum = 145;BA.debugLine="Dim lblIconoEgresos As Label";
Debug.ShouldStop(65536);
_lbliconoegresos = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("lblIconoEgresos", _lbliconoegresos);
 BA.debugLineNum = 148;BA.debugLine="Dim cd As ColorDrawable";
Debug.ShouldStop(524288);
_cd = RemoteObject.createNew ("anywheresoftware.b4a.objects.drawable.ColorDrawable");Debug.locals.put("cd", _cd);
 BA.debugLineNum = 149;BA.debugLine="cd.Initialize(Colors.White, 20)";
Debug.ShouldStop(1048576);
_cd.runVoidMethod ("Initialize",(Object)(historiales.mostCurrent.__c.getField(false,"Colors").getField(true,"White")),(Object)(BA.numberCast(int.class, 20)));
 BA.debugLineNum = 154;BA.debugLine="pnlHistorial.Initialize(\"pnlHistorial\")";
Debug.ShouldStop(33554432);
_pnlhistorial.runVoidMethod ("Initialize",historiales.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("pnlHistorial")));
 BA.debugLineNum = 155;BA.debugLine="pnlHistorial.Top = top";
Debug.ShouldStop(67108864);
_pnlhistorial.runMethod(true,"setTop",_top);
 BA.debugLineNum = 156;BA.debugLine="pnlHistorial.Background = cd";
Debug.ShouldStop(134217728);
_pnlhistorial.runMethod(false,"setBackground",(_cd.getObject()));
 BA.debugLineNum = 157;BA.debugLine="pnlHistorial.Width = anchoDispositivo * 0.9";
Debug.ShouldStop(268435456);
_pnlhistorial.runMethod(true,"setWidth",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {historiales._anchodispositivo,RemoteObject.createImmutable(0.9)}, "*",0, 0)));
 BA.debugLineNum = 158;BA.debugLine="pnlHistorial.Height = alturaDispositivo * 0.2";
Debug.ShouldStop(536870912);
_pnlhistorial.runMethod(true,"setHeight",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {historiales._alturadispositivo,RemoteObject.createImmutable(0.2)}, "*",0, 0)));
 BA.debugLineNum = 159;BA.debugLine="pnlHistorial.Left = (anchoDispositivo - pnlHistor";
Debug.ShouldStop(1073741824);
_pnlhistorial.runMethod(true,"setLeft",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {(RemoteObject.solve(new RemoteObject[] {historiales._anchodispositivo,_pnlhistorial.runMethod(true,"getWidth")}, "-",1, 1)),RemoteObject.createImmutable(2)}, "/",0, 0)));
 BA.debugLineNum = 160;BA.debugLine="pnlHistorial.Width = anchoDispositivo * 0.9";
Debug.ShouldStop(-2147483648);
_pnlhistorial.runMethod(true,"setWidth",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {historiales._anchodispositivo,RemoteObject.createImmutable(0.9)}, "*",0, 0)));
 BA.debugLineNum = 164;BA.debugLine="lblBalance.Initialize(\"lblBalance\")";
Debug.ShouldStop(8);
_lblbalance.runVoidMethod ("Initialize",historiales.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("lblBalance")));
 BA.debugLineNum = 165;BA.debugLine="lblBalance.Text = cs.Initialize.Color(Colors.Blac";
Debug.ShouldStop(16);
_lblbalance.runMethod(true,"setText",BA.ObjectToCharSequence(historiales.mostCurrent._cs.runMethod(false,"Initialize").runMethod(false,"Color",(Object)(historiales.mostCurrent.__c.getField(false,"Colors").getField(true,"Black"))).runMethod(false,"Alignment",(Object)(BA.getEnumFromString(BA.getDeviceClass("android.text.Layout.Alignment"),RemoteObject.createImmutable("ALIGN_CENTER")))).runMethod(false,"Typeface",(Object)(historiales.mostCurrent.__c.getField(false,"Typeface").getField(false,"DEFAULT"))).runMethod(false,"Size",(Object)(BA.numberCast(int.class, 14))).runMethod(false,"Append",(Object)(BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable("Balance:"),historiales.mostCurrent.__c.getField(true,"CRLF"))))).runMethod(false,"Typeface",(Object)(historiales.mostCurrent.__c.getField(false,"Typeface").getField(false,"DEFAULT"))).runMethod(false,"Size",(Object)(BA.numberCast(int.class, 16))).runMethod(false,"Append",(Object)(BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable("$"),_datos.getField(true,"balance" /*RemoteObject*/ ))))).runMethod(false,"PopAll").getObject()));
 BA.debugLineNum = 166;BA.debugLine="lblBalance.Height = pnlHistorial.Height * 0.4";
Debug.ShouldStop(32);
_lblbalance.runMethod(true,"setHeight",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {_pnlhistorial.runMethod(true,"getHeight"),RemoteObject.createImmutable(0.4)}, "*",0, 0)));
 BA.debugLineNum = 167;BA.debugLine="lblBalance.Top = 0";
Debug.ShouldStop(64);
_lblbalance.runMethod(true,"setTop",BA.numberCast(int.class, 0));
 BA.debugLineNum = 168;BA.debugLine="lblBalance.Gravity = Gravity.CENTER";
Debug.ShouldStop(128);
_lblbalance.runMethod(true,"setGravity",historiales.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER"));
 BA.debugLineNum = 169;BA.debugLine="pnlHistorial.AddView(lblBalance, lblBalance.Left,";
Debug.ShouldStop(256);
_pnlhistorial.runVoidMethod ("AddView",(Object)((_lblbalance.getObject())),(Object)(_lblbalance.runMethod(true,"getLeft")),(Object)(_lblbalance.runMethod(true,"getTop")),(Object)(_lblbalance.runMethod(true,"getWidth")),(Object)(_lblbalance.runMethod(true,"getHeight")));
 BA.debugLineNum = 170;BA.debugLine="lblBalance.Width = stu.MeasureMultilineTextHeight";
Debug.ShouldStop(512);
_lblbalance.runMethod(true,"setWidth",historiales.mostCurrent._stu.runMethod(true,"MeasureMultilineTextHeight",(Object)((_lblbalance.getObject())),(Object)(BA.ObjectToCharSequence(_lblbalance.runMethod(true,"getText")))));
 BA.debugLineNum = 171;BA.debugLine="lblBalance.Left = (pnlHistorial.Width - lblBalanc";
Debug.ShouldStop(1024);
_lblbalance.runMethod(true,"setLeft",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {(RemoteObject.solve(new RemoteObject[] {_pnlhistorial.runMethod(true,"getWidth"),_lblbalance.runMethod(true,"getWidth")}, "-",1, 1)),RemoteObject.createImmutable(2)}, "/",0, 0)));
 BA.debugLineNum = 173;BA.debugLine="cd.Initialize(Colors.Transparent, 100)";
Debug.ShouldStop(4096);
_cd.runVoidMethod ("Initialize",(Object)(historiales.mostCurrent.__c.getField(false,"Colors").getField(true,"Transparent")),(Object)(BA.numberCast(int.class, 100)));
 BA.debugLineNum = 174;BA.debugLine="lblIconoIngresos.Initialize(\"lblIconoIngresos\")";
Debug.ShouldStop(8192);
_lbliconoingresos.runVoidMethod ("Initialize",historiales.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("lblIconoIngresos")));
 BA.debugLineNum = 175;BA.debugLine="lblIconoIngresos.Background = cd";
Debug.ShouldStop(16384);
_lbliconoingresos.runMethod(false,"setBackground",(_cd.getObject()));
 BA.debugLineNum = 176;BA.debugLine="lblIconoIngresos.Typeface = Typeface.MATERIALICON";
Debug.ShouldStop(32768);
_lbliconoingresos.runMethod(false,"setTypeface",historiales.mostCurrent.__c.getField(false,"Typeface").runMethod(false,"getMATERIALICONS"));
 BA.debugLineNum = 177;BA.debugLine="lblIconoIngresos.Top = lblBalance.Height";
Debug.ShouldStop(65536);
_lbliconoingresos.runMethod(true,"setTop",_lblbalance.runMethod(true,"getHeight"));
 BA.debugLineNum = 178;BA.debugLine="lblIconoIngresos.Left = pnlHistorial.Width * 0.05";
Debug.ShouldStop(131072);
_lbliconoingresos.runMethod(true,"setLeft",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {_pnlhistorial.runMethod(true,"getWidth"),RemoteObject.createImmutable(0.05)}, "*",0, 0)));
 BA.debugLineNum = 179;BA.debugLine="lblIconoIngresos.Height = pnlHistorial.Height * 0";
Debug.ShouldStop(262144);
_lbliconoingresos.runMethod(true,"setHeight",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {_pnlhistorial.runMethod(true,"getHeight"),RemoteObject.createImmutable(0.3)}, "*",0, 0)));
 BA.debugLineNum = 180;BA.debugLine="lblIconoIngresos.Width = lblIconoIngresos.Height";
Debug.ShouldStop(524288);
_lbliconoingresos.runMethod(true,"setWidth",_lbliconoingresos.runMethod(true,"getHeight"));
 BA.debugLineNum = 181;BA.debugLine="lblIconoIngresos.Text = Chr(0xE5D8)";
Debug.ShouldStop(1048576);
_lbliconoingresos.runMethod(true,"setText",BA.ObjectToCharSequence(historiales.mostCurrent.__c.runMethod(true,"Chr",(Object)(BA.numberCast(int.class, 0xe5d8)))));
 BA.debugLineNum = 182;BA.debugLine="lblIconoIngresos.TextColor = Colors.White";
Debug.ShouldStop(2097152);
_lbliconoingresos.runMethod(true,"setTextColor",historiales.mostCurrent.__c.getField(false,"Colors").getField(true,"White"));
 BA.debugLineNum = 183;BA.debugLine="lblIconoIngresos.Color = Colors.ARGB(255, 42, 197";
Debug.ShouldStop(4194304);
_lbliconoingresos.runVoidMethod ("setColor",historiales.mostCurrent.__c.getField(false,"Colors").runMethod(true,"ARGB",(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 42)),(Object)(BA.numberCast(int.class, 197)),(Object)(BA.numberCast(int.class, 33))));
 BA.debugLineNum = 184;BA.debugLine="lblIconoIngresos.Gravity = Gravity.CENTER";
Debug.ShouldStop(8388608);
_lbliconoingresos.runMethod(true,"setGravity",historiales.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER"));
 BA.debugLineNum = 185;BA.debugLine="pnlHistorial.AddView(lblIconoIngresos, lblIconoIn";
Debug.ShouldStop(16777216);
_pnlhistorial.runVoidMethod ("AddView",(Object)((_lbliconoingresos.getObject())),(Object)(_lbliconoingresos.runMethod(true,"getLeft")),(Object)(_lbliconoingresos.runMethod(true,"getTop")),(Object)(_lbliconoingresos.runMethod(true,"getWidth")),(Object)(_lbliconoingresos.runMethod(true,"getHeight")));
 BA.debugLineNum = 187;BA.debugLine="lblIngresos.Initialize(\"lblIngresos\")";
Debug.ShouldStop(67108864);
_lblingresos.runVoidMethod ("Initialize",historiales.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("lblIngresos")));
 BA.debugLineNum = 188;BA.debugLine="lblIngresos.Height = lblIconoIngresos.Height";
Debug.ShouldStop(134217728);
_lblingresos.runMethod(true,"setHeight",_lbliconoingresos.runMethod(true,"getHeight"));
 BA.debugLineNum = 189;BA.debugLine="lblIngresos.Width = pnlHistorial.Width * 0.5 - (l";
Debug.ShouldStop(268435456);
_lblingresos.runMethod(true,"setWidth",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {_pnlhistorial.runMethod(true,"getWidth"),RemoteObject.createImmutable(0.5),(RemoteObject.solve(new RemoteObject[] {_lbliconoingresos.runMethod(true,"getLeft"),_lbliconoingresos.runMethod(true,"getWidth")}, "+",1, 1))}, "*-",1, 0)));
 BA.debugLineNum = 190;BA.debugLine="lblIngresos.Left = lblIconoIngresos.Left + lblIco";
Debug.ShouldStop(536870912);
_lblingresos.runMethod(true,"setLeft",RemoteObject.solve(new RemoteObject[] {_lbliconoingresos.runMethod(true,"getLeft"),_lbliconoingresos.runMethod(true,"getWidth")}, "+",1, 1));
 BA.debugLineNum = 191;BA.debugLine="lblIngresos.Top = lblIconoIngresos.Top";
Debug.ShouldStop(1073741824);
_lblingresos.runMethod(true,"setTop",_lbliconoingresos.runMethod(true,"getTop"));
 BA.debugLineNum = 192;BA.debugLine="lblIngresos.Text = \"$\" & datos.sumaIngresos & \".0";
Debug.ShouldStop(-2147483648);
_lblingresos.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable("$"),_datos.getField(true,"sumaIngresos" /*RemoteObject*/ ),RemoteObject.createImmutable(".00"))));
 BA.debugLineNum = 193;BA.debugLine="lblIngresos.TextSize = 13";
Debug.ShouldStop(1);
_lblingresos.runMethod(true,"setTextSize",BA.numberCast(float.class, 13));
 BA.debugLineNum = 194;BA.debugLine="lblIngresos.TextColor = Colors.ARGB(255, 42, 197,";
Debug.ShouldStop(2);
_lblingresos.runMethod(true,"setTextColor",historiales.mostCurrent.__c.getField(false,"Colors").runMethod(true,"ARGB",(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 42)),(Object)(BA.numberCast(int.class, 197)),(Object)(BA.numberCast(int.class, 33))));
 BA.debugLineNum = 195;BA.debugLine="lblIngresos.Gravity = Gravity.CENTER";
Debug.ShouldStop(4);
_lblingresos.runMethod(true,"setGravity",historiales.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER"));
 BA.debugLineNum = 196;BA.debugLine="pnlHistorial.AddView(lblIngresos, lblIngresos.Lef";
Debug.ShouldStop(8);
_pnlhistorial.runVoidMethod ("AddView",(Object)((_lblingresos.getObject())),(Object)(_lblingresos.runMethod(true,"getLeft")),(Object)(_lblingresos.runMethod(true,"getTop")),(Object)(_lblingresos.runMethod(true,"getWidth")),(Object)(_lblingresos.runMethod(true,"getHeight")));
 BA.debugLineNum = 198;BA.debugLine="lblIconoEgresos.Initialize(\"lblIconoEgresos\")";
Debug.ShouldStop(32);
_lbliconoegresos.runVoidMethod ("Initialize",historiales.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("lblIconoEgresos")));
 BA.debugLineNum = 199;BA.debugLine="lblIconoEgresos.Background = cd";
Debug.ShouldStop(64);
_lbliconoegresos.runMethod(false,"setBackground",(_cd.getObject()));
 BA.debugLineNum = 200;BA.debugLine="lblIconoEgresos.Typeface = Typeface.MATERIALICONS";
Debug.ShouldStop(128);
_lbliconoegresos.runMethod(false,"setTypeface",historiales.mostCurrent.__c.getField(false,"Typeface").runMethod(false,"getMATERIALICONS"));
 BA.debugLineNum = 201;BA.debugLine="lblIconoEgresos.Top = lblIconoIngresos.Top";
Debug.ShouldStop(256);
_lbliconoegresos.runMethod(true,"setTop",_lbliconoingresos.runMethod(true,"getTop"));
 BA.debugLineNum = 202;BA.debugLine="lblIconoEgresos.Left = pnlHistorial.Width * 0.5 +";
Debug.ShouldStop(512);
_lbliconoegresos.runMethod(true,"setLeft",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {_pnlhistorial.runMethod(true,"getWidth"),RemoteObject.createImmutable(0.5),_lbliconoingresos.runMethod(true,"getLeft")}, "*+",1, 0)));
 BA.debugLineNum = 203;BA.debugLine="lblIconoEgresos.Height = lblIconoIngresos.Height";
Debug.ShouldStop(1024);
_lbliconoegresos.runMethod(true,"setHeight",_lbliconoingresos.runMethod(true,"getHeight"));
 BA.debugLineNum = 204;BA.debugLine="lblIconoEgresos.Width = lblIconoIngresos.Width";
Debug.ShouldStop(2048);
_lbliconoegresos.runMethod(true,"setWidth",_lbliconoingresos.runMethod(true,"getWidth"));
 BA.debugLineNum = 205;BA.debugLine="lblIconoEgresos.Text = Chr(0xE5DB)";
Debug.ShouldStop(4096);
_lbliconoegresos.runMethod(true,"setText",BA.ObjectToCharSequence(historiales.mostCurrent.__c.runMethod(true,"Chr",(Object)(BA.numberCast(int.class, 0xe5db)))));
 BA.debugLineNum = 206;BA.debugLine="lblIconoEgresos.TextColor = Colors.White";
Debug.ShouldStop(8192);
_lbliconoegresos.runMethod(true,"setTextColor",historiales.mostCurrent.__c.getField(false,"Colors").getField(true,"White"));
 BA.debugLineNum = 207;BA.debugLine="lblIconoEgresos.Color = Colors.Red";
Debug.ShouldStop(16384);
_lbliconoegresos.runVoidMethod ("setColor",historiales.mostCurrent.__c.getField(false,"Colors").getField(true,"Red"));
 BA.debugLineNum = 208;BA.debugLine="lblIconoEgresos.Gravity = Gravity.CENTER";
Debug.ShouldStop(32768);
_lbliconoegresos.runMethod(true,"setGravity",historiales.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER"));
 BA.debugLineNum = 209;BA.debugLine="pnlHistorial.AddView(lblIconoEgresos, lblIconoEgr";
Debug.ShouldStop(65536);
_pnlhistorial.runVoidMethod ("AddView",(Object)((_lbliconoegresos.getObject())),(Object)(_lbliconoegresos.runMethod(true,"getLeft")),(Object)(_lbliconoegresos.runMethod(true,"getTop")),(Object)(_lbliconoegresos.runMethod(true,"getWidth")),(Object)(_lbliconoegresos.runMethod(true,"getHeight")));
 BA.debugLineNum = 211;BA.debugLine="lblEgresos.Initialize(\"lblEgresos\")";
Debug.ShouldStop(262144);
_lblegresos.runVoidMethod ("Initialize",historiales.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("lblEgresos")));
 BA.debugLineNum = 212;BA.debugLine="lblEgresos.Height = lblIconoEgresos.Height";
Debug.ShouldStop(524288);
_lblegresos.runMethod(true,"setHeight",_lbliconoegresos.runMethod(true,"getHeight"));
 BA.debugLineNum = 213;BA.debugLine="lblEgresos.Width = lblIngresos.Width";
Debug.ShouldStop(1048576);
_lblegresos.runMethod(true,"setWidth",_lblingresos.runMethod(true,"getWidth"));
 BA.debugLineNum = 214;BA.debugLine="lblEgresos.Left = lblIconoEgresos.Left + lblIcono";
Debug.ShouldStop(2097152);
_lblegresos.runMethod(true,"setLeft",RemoteObject.solve(new RemoteObject[] {_lbliconoegresos.runMethod(true,"getLeft"),_lbliconoegresos.runMethod(true,"getWidth")}, "+",1, 1));
 BA.debugLineNum = 215;BA.debugLine="lblEgresos.Top = lblIconoEgresos.Top";
Debug.ShouldStop(4194304);
_lblegresos.runMethod(true,"setTop",_lbliconoegresos.runMethod(true,"getTop"));
 BA.debugLineNum = 216;BA.debugLine="lblEgresos.Text = \"$\" & datos.sumaEgresos & \".00\"";
Debug.ShouldStop(8388608);
_lblegresos.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable("$"),_datos.getField(true,"sumaEgresos" /*RemoteObject*/ ),RemoteObject.createImmutable(".00"))));
 BA.debugLineNum = 217;BA.debugLine="lblEgresos.TextSize = 13";
Debug.ShouldStop(16777216);
_lblegresos.runMethod(true,"setTextSize",BA.numberCast(float.class, 13));
 BA.debugLineNum = 218;BA.debugLine="lblEgresos.TextColor = Colors.Red";
Debug.ShouldStop(33554432);
_lblegresos.runMethod(true,"setTextColor",historiales.mostCurrent.__c.getField(false,"Colors").getField(true,"Red"));
 BA.debugLineNum = 219;BA.debugLine="lblEgresos.Gravity = Gravity.CENTER";
Debug.ShouldStop(67108864);
_lblegresos.runMethod(true,"setGravity",historiales.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER"));
 BA.debugLineNum = 220;BA.debugLine="pnlHistorial.AddView(lblEgresos, lblEgresos.Left,";
Debug.ShouldStop(134217728);
_pnlhistorial.runVoidMethod ("AddView",(Object)((_lblegresos.getObject())),(Object)(_lblegresos.runMethod(true,"getLeft")),(Object)(_lblegresos.runMethod(true,"getTop")),(Object)(_lblegresos.runMethod(true,"getWidth")),(Object)(_lblegresos.runMethod(true,"getHeight")));
 BA.debugLineNum = 222;BA.debugLine="lblFechaHistorial.Initialize(\"lblFechaHistorial\")";
Debug.ShouldStop(536870912);
_lblfechahistorial.runVoidMethod ("Initialize",historiales.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("lblFechaHistorial")));
 BA.debugLineNum = 223;BA.debugLine="lblFechaHistorial.TextColor = Colors.Black";
Debug.ShouldStop(1073741824);
_lblfechahistorial.runMethod(true,"setTextColor",historiales.mostCurrent.__c.getField(false,"Colors").getField(true,"Black"));
 BA.debugLineNum = 224;BA.debugLine="lblFechaHistorial.Text = cs.Initialize.Color(Colo";
Debug.ShouldStop(-2147483648);
_lblfechahistorial.runMethod(true,"setText",BA.ObjectToCharSequence(historiales.mostCurrent._cs.runMethod(false,"Initialize").runMethod(false,"Color",(Object)(historiales.mostCurrent.__c.getField(false,"Colors").getField(true,"Black"))).runMethod(false,"Typeface",(Object)(historiales.mostCurrent.__c.getField(false,"Typeface").getField(false,"DEFAULT"))).runMethod(false,"Size",(Object)(BA.numberCast(int.class, 14))).runMethod(false,"Append",(Object)(BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable("Fecha del historial:"),historiales.mostCurrent.__c.getField(true,"CRLF"))))).runMethod(false,"Append",(Object)(BA.ObjectToCharSequence(_datos.getField(true,"fechaHistorial" /*RemoteObject*/ )))).runMethod(false,"PopAll").getObject()));
 BA.debugLineNum = 225;BA.debugLine="lblFechaHistorial.Width = cvsTest.MeasureStringWi";
Debug.ShouldStop(1);
_lblfechahistorial.runMethod(true,"setWidth",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {historiales.mostCurrent._cvstest.runMethod(true,"MeasureStringWidth",(Object)(_lblfechahistorial.runMethod(true,"getText")),(Object)(historiales.mostCurrent.__c.getField(false,"Typeface").getField(false,"DEFAULT")),(Object)(BA.numberCast(float.class, 16))),RemoteObject.createImmutable(2)}, "+",1, 0)));
 BA.debugLineNum = 226;BA.debugLine="lblFechaHistorial.Height = pnlHistorial.Height *";
Debug.ShouldStop(2);
_lblfechahistorial.runMethod(true,"setHeight",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {_pnlhistorial.runMethod(true,"getHeight"),RemoteObject.createImmutable(0.3)}, "*",0, 0)));
 BA.debugLineNum = 227;BA.debugLine="lblFechaHistorial.Top = lblIconoIngresos.Top + lb";
Debug.ShouldStop(4);
_lblfechahistorial.runMethod(true,"setTop",RemoteObject.solve(new RemoteObject[] {_lbliconoingresos.runMethod(true,"getTop"),_lbliconoingresos.runMethod(true,"getHeight")}, "+",1, 1));
 BA.debugLineNum = 228;BA.debugLine="lblFechaHistorial.Left = (pnlHistorial.Width - lb";
Debug.ShouldStop(8);
_lblfechahistorial.runMethod(true,"setLeft",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {(RemoteObject.solve(new RemoteObject[] {_pnlhistorial.runMethod(true,"getWidth"),_lblfechahistorial.runMethod(true,"getWidth")}, "-",1, 1)),RemoteObject.createImmutable(0.5)}, "*",0, 0)));
 BA.debugLineNum = 229;BA.debugLine="lblFechaHistorial.Gravity = Gravity.CENTER";
Debug.ShouldStop(16);
_lblfechahistorial.runMethod(true,"setGravity",historiales.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER"));
 BA.debugLineNum = 230;BA.debugLine="pnlHistorial.AddView(lblFechaHistorial, lblFechaH";
Debug.ShouldStop(32);
_pnlhistorial.runVoidMethod ("AddView",(Object)((_lblfechahistorial.getObject())),(Object)(_lblfechahistorial.runMethod(true,"getLeft")),(Object)(_lblfechahistorial.runMethod(true,"getTop")),(Object)(_lblfechahistorial.runMethod(true,"getWidth")),(Object)(_lblfechahistorial.runMethod(true,"getHeight")));
 BA.debugLineNum = 232;BA.debugLine="lblEliminar.Initialize(\"lblEliminar\")";
Debug.ShouldStop(128);
_lbleliminar.runVoidMethod ("Initialize",historiales.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("lblEliminar")));
 BA.debugLineNum = 233;BA.debugLine="lblEliminar.Typeface = Typeface.FONTAWESOME";
Debug.ShouldStop(256);
_lbleliminar.runMethod(false,"setTypeface",historiales.mostCurrent.__c.getField(false,"Typeface").runMethod(false,"getFONTAWESOME"));
 BA.debugLineNum = 234;BA.debugLine="lblEliminar.Text = Chr(0xF1F8)";
Debug.ShouldStop(512);
_lbleliminar.runMethod(true,"setText",BA.ObjectToCharSequence(historiales.mostCurrent.__c.runMethod(true,"Chr",(Object)(BA.numberCast(int.class, 0xf1f8)))));
 BA.debugLineNum = 235;BA.debugLine="lblEliminar.TextSize = 18";
Debug.ShouldStop(1024);
_lbleliminar.runMethod(true,"setTextSize",BA.numberCast(float.class, 18));
 BA.debugLineNum = 236;BA.debugLine="lblEliminar.TextColor = Colors.Black";
Debug.ShouldStop(2048);
_lbleliminar.runMethod(true,"setTextColor",historiales.mostCurrent.__c.getField(false,"Colors").getField(true,"Black"));
 BA.debugLineNum = 237;BA.debugLine="lblEliminar.Width = cvsTest.MeasureStringWidth(lb";
Debug.ShouldStop(4096);
_lbleliminar.runMethod(true,"setWidth",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {historiales.mostCurrent._cvstest.runMethod(true,"MeasureStringWidth",(Object)(_lbleliminar.runMethod(true,"getText")),(Object)(historiales.mostCurrent.__c.getField(false,"Typeface").runMethod(false,"getFONTAWESOME")),(Object)(_lbleliminar.runMethod(true,"getTextSize"))),RemoteObject.createImmutable(2)}, "+",1, 0)));
 BA.debugLineNum = 238;BA.debugLine="lblEliminar.Left = pnlHistorial.Width - lblElimin";
Debug.ShouldStop(8192);
_lbleliminar.runMethod(true,"setLeft",RemoteObject.solve(new RemoteObject[] {_pnlhistorial.runMethod(true,"getWidth"),_lbleliminar.runMethod(true,"getWidth"),RemoteObject.createImmutable(2)}, "-*",1, 1));
 BA.debugLineNum = 239;BA.debugLine="lblEliminar.Top = lblEliminar.Width";
Debug.ShouldStop(16384);
_lbleliminar.runMethod(true,"setTop",_lbleliminar.runMethod(true,"getWidth"));
 BA.debugLineNum = 240;BA.debugLine="lblEliminar.Gravity = Gravity.CENTER";
Debug.ShouldStop(32768);
_lbleliminar.runMethod(true,"setGravity",historiales.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER"));
 BA.debugLineNum = 241;BA.debugLine="pnlHistorial.AddView(lblEliminar, lblEliminar.Lef";
Debug.ShouldStop(65536);
_pnlhistorial.runVoidMethod ("AddView",(Object)((_lbleliminar.getObject())),(Object)(_lbleliminar.runMethod(true,"getLeft")),(Object)(_lbleliminar.runMethod(true,"getTop")),(Object)(_lbleliminar.runMethod(true,"getWidth")),(Object)(_lbleliminar.runMethod(true,"getHeight")));
 BA.debugLineNum = 243;BA.debugLine="lblEliminar.Height = stu.MeasureMultilineTextHeig";
Debug.ShouldStop(262144);
_lbleliminar.runMethod(true,"setHeight",RemoteObject.solve(new RemoteObject[] {historiales.mostCurrent._stu.runMethod(true,"MeasureMultilineTextHeight",(Object)((_lbleliminar.getObject())),(Object)(BA.ObjectToCharSequence(_lbleliminar.runMethod(true,"getText")))),RemoteObject.createImmutable(2)}, "+",1, 1));
 BA.debugLineNum = 245;BA.debugLine="pnlDeslizable.AddView(pnlHistorial, pnlHistorial.";
Debug.ShouldStop(1048576);
historiales.mostCurrent._pnldeslizable.runVoidMethod ("AddView",(Object)((_pnlhistorial.getObject())),(Object)(_pnlhistorial.runMethod(true,"getLeft")),(Object)(_top),(Object)(_pnlhistorial.runMethod(true,"getWidth")),(Object)(_pnlhistorial.runMethod(true,"getHeight")));
 BA.debugLineNum = 250;BA.debugLine="Dim referencia As IndiceHistorial";
Debug.ShouldStop(33554432);
_referencia = RemoteObject.createNew ("pullup.wallet.historiales._indicehistorial");Debug.locals.put("referencia", _referencia);
 BA.debugLineNum = 251;BA.debugLine="referencia.rowid = datos.rowid";
Debug.ShouldStop(67108864);
_referencia.setField ("rowid" /*RemoteObject*/ ,_datos.getField(true,"rowid" /*RemoteObject*/ ));
 BA.debugLineNum = 253;BA.debugLine="lblEliminar.Tag = referencia";
Debug.ShouldStop(268435456);
_lbleliminar.runMethod(false,"setTag",(_referencia));
 BA.debugLineNum = 254;BA.debugLine="End Sub";
Debug.ShouldStop(536870912);
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _globals() throws Exception{
 //BA.debugLineNum = 12;BA.debugLine="Sub Globals";
 //BA.debugLineNum = 15;BA.debugLine="Type IndiceHistorial(rowid As Int)";
;
 //BA.debugLineNum = 16;BA.debugLine="Type Historial(rowid As Int, sumaIngresos As Int,";
;
 //BA.debugLineNum = 17;BA.debugLine="Dim alturaDispositivo As Int";
historiales._alturadispositivo = RemoteObject.createImmutable(0);
 //BA.debugLineNum = 18;BA.debugLine="Dim anchoDispositivo As Int";
historiales._anchodispositivo = RemoteObject.createImmutable(0);
 //BA.debugLineNum = 19;BA.debugLine="Dim nRegistros As Int";
historiales._nregistros = RemoteObject.createImmutable(0);
 //BA.debugLineNum = 20;BA.debugLine="Private btnMenu As Button";
historiales.mostCurrent._btnmenu = RemoteObject.createNew ("anywheresoftware.b4a.objects.ButtonWrapper");
 //BA.debugLineNum = 21;BA.debugLine="Private lblContornoBoton As Label";
historiales.mostCurrent._lblcontornoboton = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
 //BA.debugLineNum = 22;BA.debugLine="Private pnlNavInferior As Panel";
historiales.mostCurrent._pnlnavinferior = RemoteObject.createNew ("anywheresoftware.b4a.objects.PanelWrapper");
 //BA.debugLineNum = 23;BA.debugLine="Private pnlDeslizable As Panel";
historiales.mostCurrent._pnldeslizable = RemoteObject.createNew ("anywheresoftware.b4a.objects.PanelWrapper");
 //BA.debugLineNum = 24;BA.debugLine="Private svPantalla As ScrollView";
historiales.mostCurrent._svpantalla = RemoteObject.createNew ("anywheresoftware.b4a.objects.ScrollViewWrapper");
 //BA.debugLineNum = 25;BA.debugLine="Dim cur As Cursor";
historiales.mostCurrent._cur = RemoteObject.createNew ("anywheresoftware.b4a.sql.SQL.CursorWrapper");
 //BA.debugLineNum = 26;BA.debugLine="Dim cs As CSBuilder";
historiales.mostCurrent._cs = RemoteObject.createNew ("anywheresoftware.b4a.objects.CSBuilder");
 //BA.debugLineNum = 27;BA.debugLine="Dim cvsTest As Canvas";
historiales.mostCurrent._cvstest = RemoteObject.createNew ("anywheresoftware.b4a.objects.drawable.CanvasWrapper");
 //BA.debugLineNum = 28;BA.debugLine="Dim bmpTest As Bitmap";
historiales.mostCurrent._bmptest = RemoteObject.createNew ("anywheresoftware.b4a.objects.drawable.CanvasWrapper.BitmapWrapper");
 //BA.debugLineNum = 29;BA.debugLine="Dim stu As StringUtils";
historiales.mostCurrent._stu = RemoteObject.createNew ("anywheresoftware.b4a.objects.StringUtils");
 //BA.debugLineNum = 30;BA.debugLine="End Sub";
return RemoteObject.createImmutable("");
}
public static RemoteObject  _lbleliminar_click() throws Exception{
try {
		Debug.PushSubsStack("lblEliminar_Click (historiales) ","historiales",10,historiales.mostCurrent.activityBA,historiales.mostCurrent,257);
if (RapidSub.canDelegate("lbleliminar_click")) { return pullup.wallet.historiales.remoteMe.runUserSub(false, "historiales","lbleliminar_click");}
RemoteObject _lbleliminar = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _indice = RemoteObject.declareNull("pullup.wallet.historiales._indicehistorial");
RemoteObject _idregistro = RemoteObject.createImmutable(0);
RemoteObject _resultado = RemoteObject.createImmutable(0);
 BA.debugLineNum = 257;BA.debugLine="Sub lblEliminar_Click";
Debug.ShouldStop(1);
 BA.debugLineNum = 258;BA.debugLine="Dim lblEliminar As Label";
Debug.ShouldStop(2);
_lbleliminar = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("lblEliminar", _lbleliminar);
 BA.debugLineNum = 259;BA.debugLine="Dim indice As IndiceHistorial";
Debug.ShouldStop(4);
_indice = RemoteObject.createNew ("pullup.wallet.historiales._indicehistorial");Debug.locals.put("indice", _indice);
 BA.debugLineNum = 260;BA.debugLine="Dim idRegistro As Int";
Debug.ShouldStop(8);
_idregistro = RemoteObject.createImmutable(0);Debug.locals.put("idRegistro", _idregistro);
 BA.debugLineNum = 262;BA.debugLine="lblEliminar = Sender";
Debug.ShouldStop(32);
_lbleliminar = RemoteObject.declareNull("anywheresoftware.b4a.AbsObjectWrapper").runMethod(false, "ConvertToWrapper", RemoteObject.createNew("anywheresoftware.b4a.objects.LabelWrapper"), historiales.mostCurrent.__c.runMethod(false,"Sender",historiales.mostCurrent.activityBA));
 BA.debugLineNum = 263;BA.debugLine="indice = lblEliminar.Tag";
Debug.ShouldStop(64);
_indice = (_lbleliminar.runMethod(false,"getTag"));Debug.locals.put("indice", _indice);
 BA.debugLineNum = 265;BA.debugLine="lblEliminar = Sender";
Debug.ShouldStop(256);
_lbleliminar = RemoteObject.declareNull("anywheresoftware.b4a.AbsObjectWrapper").runMethod(false, "ConvertToWrapper", RemoteObject.createNew("anywheresoftware.b4a.objects.LabelWrapper"), historiales.mostCurrent.__c.runMethod(false,"Sender",historiales.mostCurrent.activityBA));
 BA.debugLineNum = 267;BA.debugLine="indice = lblEliminar.Tag";
Debug.ShouldStop(1024);
_indice = (_lbleliminar.runMethod(false,"getTag"));Debug.locals.put("indice", _indice);
 BA.debugLineNum = 269;BA.debugLine="idRegistro = indice.rowid";
Debug.ShouldStop(4096);
_idregistro = _indice.getField(true,"rowid" /*RemoteObject*/ );Debug.locals.put("idRegistro", _idregistro);
 BA.debugLineNum = 272;BA.debugLine="Log(idRegistro)";
Debug.ShouldStop(32768);
historiales.mostCurrent.__c.runVoidMethod ("LogImpl","510616847",BA.NumberToString(_idregistro),0);
 BA.debugLineNum = 273;BA.debugLine="Dim resultado As Int";
Debug.ShouldStop(65536);
_resultado = RemoteObject.createImmutable(0);Debug.locals.put("resultado", _resultado);
 BA.debugLineNum = 274;BA.debugLine="resultado = Msgbox2(\"¿Estás seguro?\", \"Eliminar h";
Debug.ShouldStop(131072);
_resultado = historiales.mostCurrent.__c.runMethodAndSync(true,"Msgbox2",(Object)(BA.ObjectToCharSequence("¿Estás seguro?")),(Object)(BA.ObjectToCharSequence("Eliminar historial")),(Object)(BA.ObjectToString("Sí")),(Object)(BA.ObjectToString("")),(Object)(BA.ObjectToString("No")),(Object)((historiales.mostCurrent.__c.getField(false,"Null"))),historiales.mostCurrent.activityBA);Debug.locals.put("resultado", _resultado);
 BA.debugLineNum = 275;BA.debugLine="If (resultado = DialogResponse.POSITIVE) Then";
Debug.ShouldStop(262144);
if ((RemoteObject.solveBoolean("=",_resultado,BA.numberCast(double.class, historiales.mostCurrent.__c.getField(false,"DialogResponse").getField(true,"POSITIVE"))))) { 
 BA.debugLineNum = 277;BA.debugLine="sql.ExecNonQuery(\"DELETE FROM historial_balance";
Debug.ShouldStop(1048576);
historiales._sql.runVoidMethod ("ExecNonQuery",(Object)(RemoteObject.concat(RemoteObject.createImmutable("DELETE FROM historial_balance WHERE id_historial = '"),_idregistro,RemoteObject.createImmutable("'"))));
 BA.debugLineNum = 280;BA.debugLine="Activity.Finish";
Debug.ShouldStop(8388608);
historiales.mostCurrent._activity.runVoidMethod ("Finish");
 BA.debugLineNum = 281;BA.debugLine="StartActivity(Me)";
Debug.ShouldStop(16777216);
historiales.mostCurrent.__c.runVoidMethod ("StartActivity",historiales.processBA,(Object)(historiales.getObject()));
 };
 BA.debugLineNum = 283;BA.debugLine="End Sub";
Debug.ShouldStop(67108864);
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _process_globals() throws Exception{
 //BA.debugLineNum = 6;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 9;BA.debugLine="Dim sql As SQL";
historiales._sql = RemoteObject.createNew ("anywheresoftware.b4a.sql.SQL");
 //BA.debugLineNum = 10;BA.debugLine="End Sub";
return RemoteObject.createImmutable("");
}
}