package pullup.wallet;

import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.pc.*;

public class ingresosunicos_subs_0 {


public static RemoteObject  _activity_create(RemoteObject _firsttime) throws Exception{
try {
		Debug.PushSubsStack("Activity_Create (ingresosunicos) ","ingresosunicos",12,ingresosunicos.mostCurrent.activityBA,ingresosunicos.mostCurrent,36);
if (RapidSub.canDelegate("activity_create")) { return pullup.wallet.ingresosunicos.remoteMe.runUserSub(false, "ingresosunicos","activity_create", _firsttime);}
RemoteObject _lblseccion = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _top = RemoteObject.createImmutable(0);
int _id = 0;
RemoteObject _datosingresounico = RemoteObject.declareNull("pullup.wallet.ingresosunicos._ingresounico");
RemoteObject _lblmensaje = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
Debug.locals.put("FirstTime", _firsttime);
 BA.debugLineNum = 36;BA.debugLine="Sub Activity_Create(FirstTime As Boolean)";
Debug.ShouldStop(8);
 BA.debugLineNum = 39;BA.debugLine="Activity.LoadLayout(\"LDeslizable\")";
Debug.ShouldStop(64);
ingresosunicos.mostCurrent._activity.runMethodAndSync(false,"LoadLayout",(Object)(RemoteObject.createImmutable("LDeslizable")),ingresosunicos.mostCurrent.activityBA);
 BA.debugLineNum = 40;BA.debugLine="Activity.Color = Colors.ARGB(255, 233, 236, 239)";
Debug.ShouldStop(128);
ingresosunicos.mostCurrent._activity.runVoidMethod ("setColor",ingresosunicos.mostCurrent.__c.getField(false,"Colors").runMethod(true,"ARGB",(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 233)),(Object)(BA.numberCast(int.class, 236)),(Object)(BA.numberCast(int.class, 239))));
 BA.debugLineNum = 41;BA.debugLine="alturaDispositivo = Main.alturaDispositivo";
Debug.ShouldStop(256);
ingresosunicos._alturadispositivo = ingresosunicos.mostCurrent._main._alturadispositivo /*RemoteObject*/ ;
 BA.debugLineNum = 42;BA.debugLine="anchoDispositivo = Main.anchoDispositivo";
Debug.ShouldStop(512);
ingresosunicos._anchodispositivo = ingresosunicos.mostCurrent._main._anchodispositivo /*RemoteObject*/ ;
 BA.debugLineNum = 43;BA.debugLine="sql = Starter.sql";
Debug.ShouldStop(1024);
ingresosunicos._sql = ingresosunicos.mostCurrent._starter._sql /*RemoteObject*/ ;
 BA.debugLineNum = 44;BA.debugLine="bmpTest.InitializeMutable(1dip, 1dip)";
Debug.ShouldStop(2048);
ingresosunicos.mostCurrent._bmptest.runVoidMethod ("InitializeMutable",(Object)(ingresosunicos.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 1)))),(Object)(ingresosunicos.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 1)))));
 BA.debugLineNum = 45;BA.debugLine="cvsTest.Initialize2(bmpTest)";
Debug.ShouldStop(4096);
ingresosunicos.mostCurrent._cvstest.runVoidMethod ("Initialize2",(Object)((ingresosunicos.mostCurrent._bmptest.getObject())));
 BA.debugLineNum = 48;BA.debugLine="pnlNavInferior.Height = alturaDispositivo * 0.08";
Debug.ShouldStop(32768);
ingresosunicos.mostCurrent._pnlnavinferior.runMethod(true,"setHeight",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {ingresosunicos._alturadispositivo,RemoteObject.createImmutable(0.08)}, "*",0, 0)));
 BA.debugLineNum = 49;BA.debugLine="pnlNavInferior.Width = anchoDispositivo";
Debug.ShouldStop(65536);
ingresosunicos.mostCurrent._pnlnavinferior.runMethod(true,"setWidth",ingresosunicos._anchodispositivo);
 BA.debugLineNum = 50;BA.debugLine="pnlNavInferior.Left = 0";
Debug.ShouldStop(131072);
ingresosunicos.mostCurrent._pnlnavinferior.runMethod(true,"setLeft",BA.numberCast(int.class, 0));
 BA.debugLineNum = 51;BA.debugLine="pnlNavInferior.Top = alturaDispositivo - pnlNavIn";
Debug.ShouldStop(262144);
ingresosunicos.mostCurrent._pnlnavinferior.runMethod(true,"setTop",RemoteObject.solve(new RemoteObject[] {ingresosunicos._alturadispositivo,ingresosunicos.mostCurrent._pnlnavinferior.runMethod(true,"getHeight")}, "-",1, 1));
 BA.debugLineNum = 54;BA.debugLine="btnMenu.Width = anchoDispositivo * 0.15";
Debug.ShouldStop(2097152);
ingresosunicos.mostCurrent._btnmenu.runMethod(true,"setWidth",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {ingresosunicos._anchodispositivo,RemoteObject.createImmutable(0.15)}, "*",0, 0)));
 BA.debugLineNum = 55;BA.debugLine="btnMenu.Height = btnMenu.Width";
Debug.ShouldStop(4194304);
ingresosunicos.mostCurrent._btnmenu.runMethod(true,"setHeight",ingresosunicos.mostCurrent._btnmenu.runMethod(true,"getWidth"));
 BA.debugLineNum = 56;BA.debugLine="btnMenu.Top = pnlNavInferior.Top - btnMenu.Height";
Debug.ShouldStop(8388608);
ingresosunicos.mostCurrent._btnmenu.runMethod(true,"setTop",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {ingresosunicos.mostCurrent._pnlnavinferior.runMethod(true,"getTop"),ingresosunicos.mostCurrent._btnmenu.runMethod(true,"getHeight"),RemoteObject.createImmutable(2)}, "-/",1, 0)));
 BA.debugLineNum = 57;BA.debugLine="btnMenu.Left = (anchoDispositivo - btnMenu.Width)";
Debug.ShouldStop(16777216);
ingresosunicos.mostCurrent._btnmenu.runMethod(true,"setLeft",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {(RemoteObject.solve(new RemoteObject[] {ingresosunicos._anchodispositivo,ingresosunicos.mostCurrent._btnmenu.runMethod(true,"getWidth")}, "-",1, 1)),RemoteObject.createImmutable(2)}, "/",0, 0)));
 BA.debugLineNum = 59;BA.debugLine="lblContornoBoton.Width = anchoDispositivo * 0.17";
Debug.ShouldStop(67108864);
ingresosunicos.mostCurrent._lblcontornoboton.runMethod(true,"setWidth",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {ingresosunicos._anchodispositivo,RemoteObject.createImmutable(0.17)}, "*",0, 0)));
 BA.debugLineNum = 60;BA.debugLine="lblContornoBoton.Height = lblContornoBoton.Width";
Debug.ShouldStop(134217728);
ingresosunicos.mostCurrent._lblcontornoboton.runMethod(true,"setHeight",ingresosunicos.mostCurrent._lblcontornoboton.runMethod(true,"getWidth"));
 BA.debugLineNum = 61;BA.debugLine="lblContornoBoton.Left = (anchoDispositivo - lblCo";
Debug.ShouldStop(268435456);
ingresosunicos.mostCurrent._lblcontornoboton.runMethod(true,"setLeft",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {(RemoteObject.solve(new RemoteObject[] {ingresosunicos._anchodispositivo,ingresosunicos.mostCurrent._lblcontornoboton.runMethod(true,"getWidth")}, "-",1, 1)),RemoteObject.createImmutable(2)}, "/",0, 0)));
 BA.debugLineNum = 62;BA.debugLine="lblContornoBoton.Top = pnlNavInferior.Top - lblCo";
Debug.ShouldStop(536870912);
ingresosunicos.mostCurrent._lblcontornoboton.runMethod(true,"setTop",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {ingresosunicos.mostCurrent._pnlnavinferior.runMethod(true,"getTop"),ingresosunicos.mostCurrent._lblcontornoboton.runMethod(true,"getHeight"),RemoteObject.createImmutable(2)}, "-/",1, 0)));
 BA.debugLineNum = 66;BA.debugLine="svPantalla.Height = pnlNavInferior.Top";
Debug.ShouldStop(2);
ingresosunicos.mostCurrent._svpantalla.runMethod(true,"setHeight",ingresosunicos.mostCurrent._pnlnavinferior.runMethod(true,"getTop"));
 BA.debugLineNum = 67;BA.debugLine="svPantalla.Panel.LoadLayout(\"LPantallaDeslizable\"";
Debug.ShouldStop(4);
ingresosunicos.mostCurrent._svpantalla.runMethod(false,"getPanel").runMethodAndSync(false,"LoadLayout",(Object)(RemoteObject.createImmutable("LPantallaDeslizable")),ingresosunicos.mostCurrent.activityBA);
 BA.debugLineNum = 68;BA.debugLine="svPantalla.Width = anchoDispositivo * 1.5";
Debug.ShouldStop(8);
ingresosunicos.mostCurrent._svpantalla.runMethod(true,"setWidth",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {ingresosunicos._anchodispositivo,RemoteObject.createImmutable(1.5)}, "*",0, 0)));
 BA.debugLineNum = 69;BA.debugLine="pnlDeslizable.Width = svPantalla.Width";
Debug.ShouldStop(16);
ingresosunicos.mostCurrent._pnldeslizable.runMethod(true,"setWidth",ingresosunicos.mostCurrent._svpantalla.runMethod(true,"getWidth"));
 BA.debugLineNum = 75;BA.debugLine="Dim lblSeccion As Label";
Debug.ShouldStop(1024);
_lblseccion = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("lblSeccion", _lblseccion);
 BA.debugLineNum = 76;BA.debugLine="lblSeccion.Initialize(\"lblSeccion\")";
Debug.ShouldStop(2048);
_lblseccion.runVoidMethod ("Initialize",ingresosunicos.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("lblSeccion")));
 BA.debugLineNum = 77;BA.debugLine="lblSeccion.Text = \"Ingresos únicos\"";
Debug.ShouldStop(4096);
_lblseccion.runMethod(true,"setText",BA.ObjectToCharSequence("Ingresos únicos"));
 BA.debugLineNum = 78;BA.debugLine="lblSeccion.TextSize = 20";
Debug.ShouldStop(8192);
_lblseccion.runMethod(true,"setTextSize",BA.numberCast(float.class, 20));
 BA.debugLineNum = 79;BA.debugLine="lblSeccion.TextColor = Colors.Black";
Debug.ShouldStop(16384);
_lblseccion.runMethod(true,"setTextColor",ingresosunicos.mostCurrent.__c.getField(false,"Colors").getField(true,"Black"));
 BA.debugLineNum = 80;BA.debugLine="lblSeccion.Height = 30dip";
Debug.ShouldStop(32768);
_lblseccion.runMethod(true,"setHeight",ingresosunicos.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 30))));
 BA.debugLineNum = 81;BA.debugLine="lblSeccion.Width = anchoDispositivo * 0.9";
Debug.ShouldStop(65536);
_lblseccion.runMethod(true,"setWidth",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {ingresosunicos._anchodispositivo,RemoteObject.createImmutable(0.9)}, "*",0, 0)));
 BA.debugLineNum = 82;BA.debugLine="lblSeccion.Top = 30dip";
Debug.ShouldStop(131072);
_lblseccion.runMethod(true,"setTop",ingresosunicos.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 30))));
 BA.debugLineNum = 83;BA.debugLine="lblSeccion.Left = (anchoDispositivo - lblSeccion.";
Debug.ShouldStop(262144);
_lblseccion.runMethod(true,"setLeft",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {(RemoteObject.solve(new RemoteObject[] {ingresosunicos._anchodispositivo,_lblseccion.runMethod(true,"getWidth")}, "-",1, 1)),RemoteObject.createImmutable(2)}, "/",0, 0)));
 BA.debugLineNum = 84;BA.debugLine="pnlDeslizable.AddView(lblSeccion, lblSeccion.Left";
Debug.ShouldStop(524288);
ingresosunicos.mostCurrent._pnldeslizable.runVoidMethod ("AddView",(Object)((_lblseccion.getObject())),(Object)(_lblseccion.runMethod(true,"getLeft")),(Object)(_lblseccion.runMethod(true,"getTop")),(Object)(_lblseccion.runMethod(true,"getWidth")),(Object)(_lblseccion.runMethod(true,"getHeight")));
 BA.debugLineNum = 89;BA.debugLine="Dim top As Int";
Debug.ShouldStop(16777216);
_top = RemoteObject.createImmutable(0);Debug.locals.put("top", _top);
 BA.debugLineNum = 90;BA.debugLine="top = lblSeccion.Top + lblSeccion.Height + 30dip";
Debug.ShouldStop(33554432);
_top = RemoteObject.solve(new RemoteObject[] {_lblseccion.runMethod(true,"getTop"),_lblseccion.runMethod(true,"getHeight"),ingresosunicos.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 30)))}, "++",2, 1);Debug.locals.put("top", _top);
 BA.debugLineNum = 93;BA.debugLine="cur = sql.ExecQuery(\"SELECT * FROM ingresos_unico";
Debug.ShouldStop(268435456);
ingresosunicos.mostCurrent._cur = RemoteObject.declareNull("anywheresoftware.b4a.AbsObjectWrapper").runMethod(false, "ConvertToWrapper", RemoteObject.createNew("anywheresoftware.b4a.sql.SQL.CursorWrapper"), ingresosunicos._sql.runMethod(false,"ExecQuery",(Object)(RemoteObject.createImmutable("SELECT * FROM ingresos_unicos ORDER BY rowid ASC"))));
 BA.debugLineNum = 94;BA.debugLine="nRegistros = cur.RowCount";
Debug.ShouldStop(536870912);
ingresosunicos._nregistros = ingresosunicos.mostCurrent._cur.runMethod(true,"getRowCount");
 BA.debugLineNum = 98;BA.debugLine="If nRegistros > 0 Then";
Debug.ShouldStop(2);
if (RemoteObject.solveBoolean(">",ingresosunicos._nregistros,BA.numberCast(double.class, 0))) { 
 BA.debugLineNum = 100;BA.debugLine="Dim Relaciones(nRegistros, 2) As B4XView";
Debug.ShouldStop(8);
ingresosunicos.mostCurrent._relaciones = RemoteObject.createNewArray ("anywheresoftware.b4a.objects.B4XViewWrapper", new int[] {ingresosunicos._nregistros.<Integer>get().intValue(),2}, new Object[]{});
 BA.debugLineNum = 101;BA.debugLine="Dim arrayPnlsOpciones(nRegistros) As B4XView";
Debug.ShouldStop(16);
ingresosunicos.mostCurrent._arraypnlsopciones = RemoteObject.createNewArray ("anywheresoftware.b4a.objects.B4XViewWrapper", new int[] {ingresosunicos._nregistros.<Integer>get().intValue()}, new Object[]{});
 BA.debugLineNum = 103;BA.debugLine="For id = 0 To nRegistros - 1";
Debug.ShouldStop(64);
{
final int step41 = 1;
final int limit41 = RemoteObject.solve(new RemoteObject[] {ingresosunicos._nregistros,RemoteObject.createImmutable(1)}, "-",1, 1).<Integer>get().intValue();
_id = 0 ;
for (;(step41 > 0 && _id <= limit41) || (step41 < 0 && _id >= limit41) ;_id = ((int)(0 + _id + step41))  ) {
Debug.locals.put("id", _id);
 BA.debugLineNum = 104;BA.debugLine="cur.Position = id";
Debug.ShouldStop(128);
ingresosunicos.mostCurrent._cur.runMethod(true,"setPosition",BA.numberCast(int.class, _id));
 BA.debugLineNum = 106;BA.debugLine="Dim datosIngresoUnico As IngresoUnico";
Debug.ShouldStop(512);
_datosingresounico = RemoteObject.createNew ("pullup.wallet.ingresosunicos._ingresounico");Debug.locals.put("datosIngresoUnico", _datosingresounico);
 BA.debugLineNum = 107;BA.debugLine="datosIngresoUnico.rowid = cur.GetInt(\"id_ingres";
Debug.ShouldStop(1024);
_datosingresounico.setField ("rowid" /*RemoteObject*/ ,ingresosunicos.mostCurrent._cur.runMethod(true,"GetInt",(Object)(RemoteObject.createImmutable("id_ingreso_unico"))));
 BA.debugLineNum = 108;BA.debugLine="datosIngresoUnico.nombre = cur.GetString(\"nombr";
Debug.ShouldStop(2048);
_datosingresounico.setField ("nombre" /*RemoteObject*/ ,ingresosunicos.mostCurrent._cur.runMethod(true,"GetString",(Object)(RemoteObject.createImmutable("nombre"))));
 BA.debugLineNum = 109;BA.debugLine="datosIngresoUnico.monto = cur.GetInt(\"monto\")";
Debug.ShouldStop(4096);
_datosingresounico.setField ("monto" /*RemoteObject*/ ,ingresosunicos.mostCurrent._cur.runMethod(true,"GetInt",(Object)(RemoteObject.createImmutable("monto"))));
 BA.debugLineNum = 110;BA.debugLine="datosIngresoUnico.descripcion = cur.GetString(\"";
Debug.ShouldStop(8192);
_datosingresounico.setField ("descripcion" /*RemoteObject*/ ,ingresosunicos.mostCurrent._cur.runMethod(true,"GetString",(Object)(RemoteObject.createImmutable("descripcion"))));
 BA.debugLineNum = 111;BA.debugLine="datosIngresoUnico.fecha = cur.GetString(\"fecha_";
Debug.ShouldStop(16384);
_datosingresounico.setField ("fecha" /*RemoteObject*/ ,ingresosunicos.mostCurrent._cur.runMethod(true,"GetString",(Object)(RemoteObject.createImmutable("fecha_registro"))));
 BA.debugLineNum = 112;BA.debugLine="datosIngresoUnico.color = cur.GetInt(\"color\")";
Debug.ShouldStop(32768);
_datosingresounico.setField ("color" /*RemoteObject*/ ,ingresosunicos.mostCurrent._cur.runMethod(true,"GetInt",(Object)(RemoteObject.createImmutable("color"))));
 BA.debugLineNum = 114;BA.debugLine="creaObjetoLista(id, top, datosIngresoUnico)";
Debug.ShouldStop(131072);
_creaobjetolista(BA.numberCast(int.class, _id),_top,_datosingresounico);
 BA.debugLineNum = 116;BA.debugLine="top = top + alturaDispositivo * 0.12 + 60";
Debug.ShouldStop(524288);
_top = BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {_top,ingresosunicos._alturadispositivo,RemoteObject.createImmutable(0.12),RemoteObject.createImmutable(60)}, "+*+",2, 0));Debug.locals.put("top", _top);
 }
}Debug.locals.put("id", _id);
;
 }else {
 BA.debugLineNum = 120;BA.debugLine="Dim lblMensaje As Label";
Debug.ShouldStop(8388608);
_lblmensaje = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("lblMensaje", _lblmensaje);
 BA.debugLineNum = 121;BA.debugLine="lblMensaje.Initialize(\"lblMensaje\")";
Debug.ShouldStop(16777216);
_lblmensaje.runVoidMethod ("Initialize",ingresosunicos.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("lblMensaje")));
 BA.debugLineNum = 122;BA.debugLine="lblMensaje.Height = alturaDispositivo * 0.2";
Debug.ShouldStop(33554432);
_lblmensaje.runMethod(true,"setHeight",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {ingresosunicos._alturadispositivo,RemoteObject.createImmutable(0.2)}, "*",0, 0)));
 BA.debugLineNum = 123;BA.debugLine="lblMensaje.Width = anchoDispositivo * 0.9";
Debug.ShouldStop(67108864);
_lblmensaje.runMethod(true,"setWidth",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {ingresosunicos._anchodispositivo,RemoteObject.createImmutable(0.9)}, "*",0, 0)));
 BA.debugLineNum = 124;BA.debugLine="lblMensaje.Top = (alturaDispositivo - lblMensaje";
Debug.ShouldStop(134217728);
_lblmensaje.runMethod(true,"setTop",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {(RemoteObject.solve(new RemoteObject[] {ingresosunicos._alturadispositivo,_lblmensaje.runMethod(true,"getHeight")}, "-",1, 1)),RemoteObject.createImmutable(2)}, "/",0, 0)));
 BA.debugLineNum = 125;BA.debugLine="lblMensaje.Left = (anchoDispositivo - lblMensaje";
Debug.ShouldStop(268435456);
_lblmensaje.runMethod(true,"setLeft",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {(RemoteObject.solve(new RemoteObject[] {ingresosunicos._anchodispositivo,_lblmensaje.runMethod(true,"getWidth")}, "-",1, 1)),RemoteObject.createImmutable(2)}, "/",0, 0)));
 BA.debugLineNum = 126;BA.debugLine="lblMensaje.Text = cs.Initialize.Color(Colors.Bla";
Debug.ShouldStop(536870912);
_lblmensaje.runMethod(true,"setText",BA.ObjectToCharSequence(ingresosunicos.mostCurrent._cs.runMethod(false,"Initialize").runMethod(false,"Color",(Object)(ingresosunicos.mostCurrent.__c.getField(false,"Colors").getField(true,"Black"))).runMethod(false,"Alignment",(Object)(BA.getEnumFromString(BA.getDeviceClass("android.text.Layout.Alignment"),RemoteObject.createImmutable("ALIGN_CENTER")))).runMethod(false,"Typeface",(Object)(ingresosunicos.mostCurrent.__c.getField(false,"Typeface").runMethod(false,"getMATERIALICONS"))).runMethod(false,"Size",(Object)(BA.numberCast(int.class, 50))).runMethod(false,"Append",(Object)(BA.ObjectToCharSequence(RemoteObject.concat(ingresosunicos.mostCurrent.__c.runMethod(true,"Chr",(Object)(BA.numberCast(int.class, 0xe89c))),ingresosunicos.mostCurrent.__c.getField(true,"CRLF"))))).runMethod(false,"Typeface",(Object)(ingresosunicos.mostCurrent.__c.getField(false,"Typeface").getField(false,"DEFAULT"))).runMethod(false,"Size",(Object)(BA.numberCast(int.class, 18))).runMethod(false,"Append",(Object)(BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable("Está muy vacío aquí adentro."),ingresosunicos.mostCurrent.__c.getField(true,"CRLF"))))).runMethod(false,"Append",(Object)(BA.ObjectToCharSequence(RemoteObject.createImmutable("Agrega un ingreso único desde el menú principal.")))).runMethod(false,"PopAll").getObject()));
 BA.debugLineNum = 127;BA.debugLine="Activity.AddView(lblMensaje, lblMensaje.Left, lb";
Debug.ShouldStop(1073741824);
ingresosunicos.mostCurrent._activity.runVoidMethod ("AddView",(Object)((_lblmensaje.getObject())),(Object)(_lblmensaje.runMethod(true,"getLeft")),(Object)(_lblmensaje.runMethod(true,"getTop")),(Object)(_lblmensaje.runMethod(true,"getWidth")),(Object)(_lblmensaje.runMethod(true,"getHeight")));
 };
 BA.debugLineNum = 130;BA.debugLine="svPantalla.Panel.Height = top + 100";
Debug.ShouldStop(2);
ingresosunicos.mostCurrent._svpantalla.runMethod(false,"getPanel").runMethod(true,"setHeight",RemoteObject.solve(new RemoteObject[] {_top,RemoteObject.createImmutable(100)}, "+",1, 1));
 BA.debugLineNum = 131;BA.debugLine="End Sub";
Debug.ShouldStop(4);
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _activity_pause(RemoteObject _userclosed) throws Exception{
try {
		Debug.PushSubsStack("Activity_Pause (ingresosunicos) ","ingresosunicos",12,ingresosunicos.mostCurrent.activityBA,ingresosunicos.mostCurrent,137);
if (RapidSub.canDelegate("activity_pause")) { return pullup.wallet.ingresosunicos.remoteMe.runUserSub(false, "ingresosunicos","activity_pause", _userclosed);}
Debug.locals.put("UserClosed", _userclosed);
 BA.debugLineNum = 137;BA.debugLine="Sub Activity_Pause (UserClosed As Boolean)";
Debug.ShouldStop(256);
 BA.debugLineNum = 139;BA.debugLine="End Sub";
Debug.ShouldStop(1024);
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _activity_resume() throws Exception{
try {
		Debug.PushSubsStack("Activity_Resume (ingresosunicos) ","ingresosunicos",12,ingresosunicos.mostCurrent.activityBA,ingresosunicos.mostCurrent,133);
if (RapidSub.canDelegate("activity_resume")) { return pullup.wallet.ingresosunicos.remoteMe.runUserSub(false, "ingresosunicos","activity_resume");}
 BA.debugLineNum = 133;BA.debugLine="Sub Activity_Resume";
Debug.ShouldStop(16);
 BA.debugLineNum = 135;BA.debugLine="End Sub";
Debug.ShouldStop(64);
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _btneditar_click() throws Exception{
try {
		Debug.PushSubsStack("btnEditar_Click (ingresosunicos) ","ingresosunicos",12,ingresosunicos.mostCurrent.activityBA,ingresosunicos.mostCurrent,301);
if (RapidSub.canDelegate("btneditar_click")) { return pullup.wallet.ingresosunicos.remoteMe.runUserSub(false, "ingresosunicos","btneditar_click");}
RemoteObject _btneditar = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
RemoteObject _pnlpadre = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
RemoteObject _idregistro = RemoteObject.createImmutable(0);
RemoteObject _indice = RemoteObject.declareNull("pullup.wallet.ingresosunicos._indiceingresounico");
 BA.debugLineNum = 301;BA.debugLine="Sub btnEditar_Click";
Debug.ShouldStop(4096);
 BA.debugLineNum = 302;BA.debugLine="Dim btnEditar As Button";
Debug.ShouldStop(8192);
_btneditar = RemoteObject.createNew ("anywheresoftware.b4a.objects.ButtonWrapper");Debug.locals.put("btnEditar", _btneditar);
 BA.debugLineNum = 303;BA.debugLine="Dim pnlPadre As Panel";
Debug.ShouldStop(16384);
_pnlpadre = RemoteObject.createNew ("anywheresoftware.b4a.objects.PanelWrapper");Debug.locals.put("pnlPadre", _pnlpadre);
 BA.debugLineNum = 304;BA.debugLine="Dim idRegistro As Int";
Debug.ShouldStop(32768);
_idregistro = RemoteObject.createImmutable(0);Debug.locals.put("idRegistro", _idregistro);
 BA.debugLineNum = 305;BA.debugLine="Dim indice As IndiceIngresoUnico";
Debug.ShouldStop(65536);
_indice = RemoteObject.createNew ("pullup.wallet.ingresosunicos._indiceingresounico");Debug.locals.put("indice", _indice);
 BA.debugLineNum = 308;BA.debugLine="btnEditar = Sender";
Debug.ShouldStop(524288);
_btneditar = RemoteObject.declareNull("anywheresoftware.b4a.AbsObjectWrapper").runMethod(false, "ConvertToWrapper", RemoteObject.createNew("anywheresoftware.b4a.objects.ButtonWrapper"), ingresosunicos.mostCurrent.__c.runMethod(false,"Sender",ingresosunicos.mostCurrent.activityBA));
 BA.debugLineNum = 310;BA.debugLine="pnlPadre = btnEditar.Parent";
Debug.ShouldStop(2097152);
_pnlpadre = RemoteObject.declareNull("anywheresoftware.b4a.AbsObjectWrapper").runMethod(false, "ConvertToWrapper", RemoteObject.createNew("anywheresoftware.b4a.objects.PanelWrapper"), _btneditar.runMethod(false,"getParent"));
 BA.debugLineNum = 312;BA.debugLine="indice = pnlPadre.Tag";
Debug.ShouldStop(8388608);
_indice = (_pnlpadre.runMethod(false,"getTag"));Debug.locals.put("indice", _indice);
 BA.debugLineNum = 314;BA.debugLine="idRegistro = indice.rowid";
Debug.ShouldStop(33554432);
_idregistro = _indice.getField(true,"rowid" /*RemoteObject*/ );Debug.locals.put("idRegistro", _idregistro);
 BA.debugLineNum = 315;BA.debugLine="CallSubDelayed2(editarIngresoUnico, \"consultaAEdi";
Debug.ShouldStop(67108864);
ingresosunicos.mostCurrent.__c.runVoidMethod ("CallSubDelayed2",ingresosunicos.processBA,(Object)((ingresosunicos.mostCurrent._editaringresounico.getObject())),(Object)(BA.ObjectToString("consultaAEditar")),(Object)((_idregistro)));
 BA.debugLineNum = 316;BA.debugLine="Activity.Finish";
Debug.ShouldStop(134217728);
ingresosunicos.mostCurrent._activity.runVoidMethod ("Finish");
 BA.debugLineNum = 317;BA.debugLine="End Sub";
Debug.ShouldStop(268435456);
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _btneliminar_click() throws Exception{
try {
		Debug.PushSubsStack("btnEliminar_Click (ingresosunicos) ","ingresosunicos",12,ingresosunicos.mostCurrent.activityBA,ingresosunicos.mostCurrent,319);
if (RapidSub.canDelegate("btneliminar_click")) { return pullup.wallet.ingresosunicos.remoteMe.runUserSub(false, "ingresosunicos","btneliminar_click");}
RemoteObject _btneliminar = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
RemoteObject _pnlpadre = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
RemoteObject _idregistro = RemoteObject.createImmutable(0);
RemoteObject _indice = RemoteObject.declareNull("pullup.wallet.ingresosunicos._indiceingresounico");
RemoteObject _resultado = RemoteObject.createImmutable(0);
 BA.debugLineNum = 319;BA.debugLine="Sub btnEliminar_Click";
Debug.ShouldStop(1073741824);
 BA.debugLineNum = 320;BA.debugLine="Dim btnEliminar As Button";
Debug.ShouldStop(-2147483648);
_btneliminar = RemoteObject.createNew ("anywheresoftware.b4a.objects.ButtonWrapper");Debug.locals.put("btnEliminar", _btneliminar);
 BA.debugLineNum = 321;BA.debugLine="Dim pnlPadre As Panel";
Debug.ShouldStop(1);
_pnlpadre = RemoteObject.createNew ("anywheresoftware.b4a.objects.PanelWrapper");Debug.locals.put("pnlPadre", _pnlpadre);
 BA.debugLineNum = 322;BA.debugLine="Dim idRegistro As Int";
Debug.ShouldStop(2);
_idregistro = RemoteObject.createImmutable(0);Debug.locals.put("idRegistro", _idregistro);
 BA.debugLineNum = 323;BA.debugLine="Dim indice As IndiceIngresoUnico";
Debug.ShouldStop(4);
_indice = RemoteObject.createNew ("pullup.wallet.ingresosunicos._indiceingresounico");Debug.locals.put("indice", _indice);
 BA.debugLineNum = 326;BA.debugLine="btnEliminar = Sender";
Debug.ShouldStop(32);
_btneliminar = RemoteObject.declareNull("anywheresoftware.b4a.AbsObjectWrapper").runMethod(false, "ConvertToWrapper", RemoteObject.createNew("anywheresoftware.b4a.objects.ButtonWrapper"), ingresosunicos.mostCurrent.__c.runMethod(false,"Sender",ingresosunicos.mostCurrent.activityBA));
 BA.debugLineNum = 328;BA.debugLine="pnlPadre = btnEliminar.Parent";
Debug.ShouldStop(128);
_pnlpadre = RemoteObject.declareNull("anywheresoftware.b4a.AbsObjectWrapper").runMethod(false, "ConvertToWrapper", RemoteObject.createNew("anywheresoftware.b4a.objects.PanelWrapper"), _btneliminar.runMethod(false,"getParent"));
 BA.debugLineNum = 330;BA.debugLine="indice = pnlPadre.Tag";
Debug.ShouldStop(512);
_indice = (_pnlpadre.runMethod(false,"getTag"));Debug.locals.put("indice", _indice);
 BA.debugLineNum = 332;BA.debugLine="idRegistro = indice.rowid";
Debug.ShouldStop(2048);
_idregistro = _indice.getField(true,"rowid" /*RemoteObject*/ );Debug.locals.put("idRegistro", _idregistro);
 BA.debugLineNum = 335;BA.debugLine="Dim resultado As Int";
Debug.ShouldStop(16384);
_resultado = RemoteObject.createImmutable(0);Debug.locals.put("resultado", _resultado);
 BA.debugLineNum = 336;BA.debugLine="resultado = Msgbox2(\"¿Estás seguro?\", \"Eliminar i";
Debug.ShouldStop(32768);
_resultado = ingresosunicos.mostCurrent.__c.runMethodAndSync(true,"Msgbox2",(Object)(BA.ObjectToCharSequence("¿Estás seguro?")),(Object)(BA.ObjectToCharSequence("Eliminar ingreso único")),(Object)(BA.ObjectToString("Sí")),(Object)(BA.ObjectToString("")),(Object)(BA.ObjectToString("No")),(Object)((ingresosunicos.mostCurrent.__c.getField(false,"Null"))),ingresosunicos.mostCurrent.activityBA);Debug.locals.put("resultado", _resultado);
 BA.debugLineNum = 337;BA.debugLine="If (resultado = DialogResponse.POSITIVE) Then";
Debug.ShouldStop(65536);
if ((RemoteObject.solveBoolean("=",_resultado,BA.numberCast(double.class, ingresosunicos.mostCurrent.__c.getField(false,"DialogResponse").getField(true,"POSITIVE"))))) { 
 BA.debugLineNum = 339;BA.debugLine="cur = sql.ExecQuery2(\"SELECT monto FROM ingresos";
Debug.ShouldStop(262144);
ingresosunicos.mostCurrent._cur = RemoteObject.declareNull("anywheresoftware.b4a.AbsObjectWrapper").runMethod(false, "ConvertToWrapper", RemoteObject.createNew("anywheresoftware.b4a.sql.SQL.CursorWrapper"), ingresosunicos._sql.runMethod(false,"ExecQuery2",(Object)(BA.ObjectToString("SELECT monto FROM ingresos_unicos WHERE id_ingreso_unico = ?")),(Object)(RemoteObject.createNewArray("String",new int[] {1},new Object[] {RemoteObject.concat(_idregistro,RemoteObject.createImmutable(""))}))));
 BA.debugLineNum = 340;BA.debugLine="cur.Position = 0";
Debug.ShouldStop(524288);
ingresosunicos.mostCurrent._cur.runMethod(true,"setPosition",BA.numberCast(int.class, 0));
 BA.debugLineNum = 341;BA.debugLine="montoSeleccionado = cur.GetInt(\"monto\")";
Debug.ShouldStop(1048576);
ingresosunicos._montoseleccionado = ingresosunicos.mostCurrent._cur.runMethod(true,"GetInt",(Object)(RemoteObject.createImmutable("monto")));
 BA.debugLineNum = 344;BA.debugLine="cur = sql.ExecQuery(\"SELECT * FROM ingresos WHER";
Debug.ShouldStop(8388608);
ingresosunicos.mostCurrent._cur = RemoteObject.declareNull("anywheresoftware.b4a.AbsObjectWrapper").runMethod(false, "ConvertToWrapper", RemoteObject.createNew("anywheresoftware.b4a.sql.SQL.CursorWrapper"), ingresosunicos._sql.runMethod(false,"ExecQuery",(Object)(RemoteObject.createImmutable("SELECT * FROM ingresos WHERE id_ingreso = 1"))));
 BA.debugLineNum = 345;BA.debugLine="cur.Position = 0";
Debug.ShouldStop(16777216);
ingresosunicos.mostCurrent._cur.runMethod(true,"setPosition",BA.numberCast(int.class, 0));
 BA.debugLineNum = 346;BA.debugLine="sumaIngresosAntigua = cur.GetInt(\"suma_ingresos\"";
Debug.ShouldStop(33554432);
ingresosunicos._sumaingresosantigua = ingresosunicos.mostCurrent._cur.runMethod(true,"GetInt",(Object)(RemoteObject.createImmutable("suma_ingresos")));
 BA.debugLineNum = 349;BA.debugLine="sumaIngresosActual = sumaIngresosAntigua - monto";
Debug.ShouldStop(268435456);
ingresosunicos._sumaingresosactual = RemoteObject.solve(new RemoteObject[] {ingresosunicos._sumaingresosantigua,ingresosunicos._montoseleccionado}, "-",1, 1);
 BA.debugLineNum = 351;BA.debugLine="sql.ExecNonQuery2(\"UPDATE ingresos SET suma_ingr";
Debug.ShouldStop(1073741824);
ingresosunicos._sql.runVoidMethod ("ExecNonQuery2",(Object)(BA.ObjectToString("UPDATE ingresos SET suma_ingresos = ? WHERE id_ingreso = 1")),(Object)(ingresosunicos.mostCurrent.__c.runMethod(false, "ArrayToList", (Object)(RemoteObject.createNewArray("Object",new int[] {1},new Object[] {(ingresosunicos._sumaingresosactual)})))));
 BA.debugLineNum = 354;BA.debugLine="sql.ExecNonQuery(\"DELETE FROM ingresos_unicos WH";
Debug.ShouldStop(2);
ingresosunicos._sql.runVoidMethod ("ExecNonQuery",(Object)(RemoteObject.concat(RemoteObject.createImmutable("DELETE FROM ingresos_unicos WHERE id_ingreso_unico = '"),_idregistro,RemoteObject.createImmutable("'"))));
 BA.debugLineNum = 357;BA.debugLine="Activity.Finish";
Debug.ShouldStop(16);
ingresosunicos.mostCurrent._activity.runVoidMethod ("Finish");
 BA.debugLineNum = 358;BA.debugLine="StartActivity(Me)";
Debug.ShouldStop(32);
ingresosunicos.mostCurrent.__c.runVoidMethod ("StartActivity",ingresosunicos.processBA,(Object)(ingresosunicos.getObject()));
 };
 BA.debugLineNum = 360;BA.debugLine="End Sub";
Debug.ShouldStop(128);
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _btnmenu_click() throws Exception{
try {
		Debug.PushSubsStack("btnMenu_Click (ingresosunicos) ","ingresosunicos",12,ingresosunicos.mostCurrent.activityBA,ingresosunicos.mostCurrent,141);
if (RapidSub.canDelegate("btnmenu_click")) { return pullup.wallet.ingresosunicos.remoteMe.runUserSub(false, "ingresosunicos","btnmenu_click");}
 BA.debugLineNum = 141;BA.debugLine="Private Sub btnMenu_Click";
Debug.ShouldStop(4096);
 BA.debugLineNum = 142;BA.debugLine="CallSubDelayed(Main, \"actualizarDatos\")";
Debug.ShouldStop(8192);
ingresosunicos.mostCurrent.__c.runVoidMethod ("CallSubDelayed",ingresosunicos.processBA,(Object)((ingresosunicos.mostCurrent._main.getObject())),(Object)(RemoteObject.createImmutable("actualizarDatos")));
 BA.debugLineNum = 143;BA.debugLine="Activity.Finish";
Debug.ShouldStop(16384);
ingresosunicos.mostCurrent._activity.runVoidMethod ("Finish");
 BA.debugLineNum = 144;BA.debugLine="End Sub";
Debug.ShouldStop(32768);
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _creaobjetolista(RemoteObject _indice,RemoteObject _top,RemoteObject _datos) throws Exception{
try {
		Debug.PushSubsStack("creaObjetoLista (ingresosunicos) ","ingresosunicos",12,ingresosunicos.mostCurrent.activityBA,ingresosunicos.mostCurrent,147);
if (RapidSub.canDelegate("creaobjetolista")) { return pullup.wallet.ingresosunicos.remoteMe.runUserSub(false, "ingresosunicos","creaobjetolista", _indice, _top, _datos);}
RemoteObject _pnlingresounico = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
RemoteObject _pnlopciones = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
RemoteObject _lblnombre = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _lblmonto = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _lbldescripcion = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _lblfecha = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _lblopciones = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _btneditar = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
RemoteObject _btneliminar = RemoteObject.declareNull("anywheresoftware.b4a.objects.ButtonWrapper");
RemoteObject _cd = RemoteObject.declareNull("anywheresoftware.b4a.objects.drawable.ColorDrawable");
RemoteObject _referencia = RemoteObject.declareNull("pullup.wallet.ingresosunicos._indiceingresounico");
RemoteObject _referencia2 = RemoteObject.declareNull("pullup.wallet.ingresosunicos._indiceingresounico");
Debug.locals.put("indice", _indice);
Debug.locals.put("top", _top);
Debug.locals.put("datos", _datos);
 BA.debugLineNum = 147;BA.debugLine="Sub creaObjetoLista(indice As Int, top As Int, dat";
Debug.ShouldStop(262144);
 BA.debugLineNum = 148;BA.debugLine="Dim pnlIngresoUnico As Panel";
Debug.ShouldStop(524288);
_pnlingresounico = RemoteObject.createNew ("anywheresoftware.b4a.objects.PanelWrapper");Debug.locals.put("pnlIngresoUnico", _pnlingresounico);
 BA.debugLineNum = 149;BA.debugLine="Dim pnlOpciones As Panel";
Debug.ShouldStop(1048576);
_pnlopciones = RemoteObject.createNew ("anywheresoftware.b4a.objects.PanelWrapper");Debug.locals.put("pnlOpciones", _pnlopciones);
 BA.debugLineNum = 150;BA.debugLine="Dim lblNombre As Label";
Debug.ShouldStop(2097152);
_lblnombre = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("lblNombre", _lblnombre);
 BA.debugLineNum = 151;BA.debugLine="Dim lblMonto As Label";
Debug.ShouldStop(4194304);
_lblmonto = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("lblMonto", _lblmonto);
 BA.debugLineNum = 152;BA.debugLine="Dim lblDescripcion As Label";
Debug.ShouldStop(8388608);
_lbldescripcion = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("lblDescripcion", _lbldescripcion);
 BA.debugLineNum = 153;BA.debugLine="Dim lblFecha As Label";
Debug.ShouldStop(16777216);
_lblfecha = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("lblFecha", _lblfecha);
 BA.debugLineNum = 154;BA.debugLine="Dim lblOpciones As Label";
Debug.ShouldStop(33554432);
_lblopciones = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("lblOpciones", _lblopciones);
 BA.debugLineNum = 155;BA.debugLine="Dim btnEditar As Button";
Debug.ShouldStop(67108864);
_btneditar = RemoteObject.createNew ("anywheresoftware.b4a.objects.ButtonWrapper");Debug.locals.put("btnEditar", _btneditar);
 BA.debugLineNum = 156;BA.debugLine="Dim btnEliminar As Button";
Debug.ShouldStop(134217728);
_btneliminar = RemoteObject.createNew ("anywheresoftware.b4a.objects.ButtonWrapper");Debug.locals.put("btnEliminar", _btneliminar);
 BA.debugLineNum = 159;BA.debugLine="Dim cd As ColorDrawable";
Debug.ShouldStop(1073741824);
_cd = RemoteObject.createNew ("anywheresoftware.b4a.objects.drawable.ColorDrawable");Debug.locals.put("cd", _cd);
 BA.debugLineNum = 160;BA.debugLine="cd.Initialize(datos.color, 20)";
Debug.ShouldStop(-2147483648);
_cd.runVoidMethod ("Initialize",(Object)(_datos.getField(true,"color" /*RemoteObject*/ )),(Object)(BA.numberCast(int.class, 20)));
 BA.debugLineNum = 163;BA.debugLine="pnlIngresoUnico.Initialize(\"pnlIngresoUnico\")";
Debug.ShouldStop(4);
_pnlingresounico.runVoidMethod ("Initialize",ingresosunicos.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("pnlIngresoUnico")));
 BA.debugLineNum = 164;BA.debugLine="pnlIngresoUnico.Top = top";
Debug.ShouldStop(8);
_pnlingresounico.runMethod(true,"setTop",_top);
 BA.debugLineNum = 165;BA.debugLine="pnlIngresoUnico.Background = cd";
Debug.ShouldStop(16);
_pnlingresounico.runMethod(false,"setBackground",(_cd.getObject()));
 BA.debugLineNum = 166;BA.debugLine="pnlIngresoUnico.Width = anchoDispositivo * 0.9";
Debug.ShouldStop(32);
_pnlingresounico.runMethod(true,"setWidth",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {ingresosunicos._anchodispositivo,RemoteObject.createImmutable(0.9)}, "*",0, 0)));
 BA.debugLineNum = 167;BA.debugLine="pnlIngresoUnico.Height = alturaDispositivo * 0.14";
Debug.ShouldStop(64);
_pnlingresounico.runMethod(true,"setHeight",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {ingresosunicos._alturadispositivo,RemoteObject.createImmutable(0.14)}, "*",0, 0)));
 BA.debugLineNum = 168;BA.debugLine="pnlIngresoUnico.Left = (anchoDispositivo - pnlIng";
Debug.ShouldStop(128);
_pnlingresounico.runMethod(true,"setLeft",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {(RemoteObject.solve(new RemoteObject[] {ingresosunicos._anchodispositivo,_pnlingresounico.runMethod(true,"getWidth")}, "-",1, 1)),RemoteObject.createImmutable(2)}, "/",0, 0)));
 BA.debugLineNum = 170;BA.debugLine="lblNombre.Initialize(\"lblNombre\")";
Debug.ShouldStop(512);
_lblnombre.runVoidMethod ("Initialize",ingresosunicos.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("lblNombre")));
 BA.debugLineNum = 171;BA.debugLine="lblNombre.TextColor = Colors.White";
Debug.ShouldStop(1024);
_lblnombre.runMethod(true,"setTextColor",ingresosunicos.mostCurrent.__c.getField(false,"Colors").getField(true,"White"));
 BA.debugLineNum = 172;BA.debugLine="lblNombre.Text = datos.nombre.ToUpperCase.CharAt(";
Debug.ShouldStop(2048);
_lblnombre.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(_datos.getField(true,"nombre" /*RemoteObject*/ ).runMethod(true,"toUpperCase").runMethod(true,"charAt",(Object)(BA.numberCast(int.class, 0))),_datos.getField(true,"nombre" /*RemoteObject*/ ).runMethod(true,"substring",(Object)(BA.numberCast(int.class, 1))).runMethod(true,"toLowerCase"))));
 BA.debugLineNum = 173;BA.debugLine="lblNombre.TextSize = 19";
Debug.ShouldStop(4096);
_lblnombre.runMethod(true,"setTextSize",BA.numberCast(float.class, 19));
 BA.debugLineNum = 174;BA.debugLine="lblNombre.Height = pnlIngresoUnico.Height * 0.3";
Debug.ShouldStop(8192);
_lblnombre.runMethod(true,"setHeight",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {_pnlingresounico.runMethod(true,"getHeight"),RemoteObject.createImmutable(0.3)}, "*",0, 0)));
 BA.debugLineNum = 175;BA.debugLine="lblNombre.Width = pnlIngresoUnico.Width * 0.9";
Debug.ShouldStop(16384);
_lblnombre.runMethod(true,"setWidth",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {_pnlingresounico.runMethod(true,"getWidth"),RemoteObject.createImmutable(0.9)}, "*",0, 0)));
 BA.debugLineNum = 176;BA.debugLine="lblNombre.Top = 0";
Debug.ShouldStop(32768);
_lblnombre.runMethod(true,"setTop",BA.numberCast(int.class, 0));
 BA.debugLineNum = 177;BA.debugLine="lblNombre.Left = pnlIngresoUnico.Width * 0.05";
Debug.ShouldStop(65536);
_lblnombre.runMethod(true,"setLeft",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {_pnlingresounico.runMethod(true,"getWidth"),RemoteObject.createImmutable(0.05)}, "*",0, 0)));
 BA.debugLineNum = 178;BA.debugLine="lblNombre.Gravity = Gravity.CENTER_VERTICAL";
Debug.ShouldStop(131072);
_lblnombre.runMethod(true,"setGravity",ingresosunicos.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER_VERTICAL"));
 BA.debugLineNum = 179;BA.debugLine="pnlIngresoUnico.AddView(lblNombre, lblNombre.Left";
Debug.ShouldStop(262144);
_pnlingresounico.runVoidMethod ("AddView",(Object)((_lblnombre.getObject())),(Object)(_lblnombre.runMethod(true,"getLeft")),(Object)(_lblnombre.runMethod(true,"getTop")),(Object)(_lblnombre.runMethod(true,"getWidth")),(Object)(_lblnombre.runMethod(true,"getHeight")));
 BA.debugLineNum = 181;BA.debugLine="lblDescripcion.Initialize(\"lblDescripcion\")";
Debug.ShouldStop(1048576);
_lbldescripcion.runVoidMethod ("Initialize",ingresosunicos.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("lblDescripcion")));
 BA.debugLineNum = 182;BA.debugLine="lblDescripcion.Text = datos.descripcion.ToUpperCa";
Debug.ShouldStop(2097152);
_lbldescripcion.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(_datos.getField(true,"descripcion" /*RemoteObject*/ ).runMethod(true,"toUpperCase").runMethod(true,"charAt",(Object)(BA.numberCast(int.class, 0))),_datos.getField(true,"descripcion" /*RemoteObject*/ ).runMethod(true,"substring",(Object)(BA.numberCast(int.class, 1))).runMethod(true,"toLowerCase"))));
 BA.debugLineNum = 183;BA.debugLine="lblDescripcion.TextColor = Colors.White";
Debug.ShouldStop(4194304);
_lbldescripcion.runMethod(true,"setTextColor",ingresosunicos.mostCurrent.__c.getField(false,"Colors").getField(true,"White"));
 BA.debugLineNum = 184;BA.debugLine="lblDescripcion.Height = pnlIngresoUnico.Height *";
Debug.ShouldStop(8388608);
_lbldescripcion.runMethod(true,"setHeight",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {_pnlingresounico.runMethod(true,"getHeight"),RemoteObject.createImmutable(0.3)}, "*",0, 0)));
 BA.debugLineNum = 185;BA.debugLine="lblDescripcion.Width = pnlIngresoUnico.Width * 0.";
Debug.ShouldStop(16777216);
_lbldescripcion.runMethod(true,"setWidth",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {_pnlingresounico.runMethod(true,"getWidth"),RemoteObject.createImmutable(0.9)}, "*",0, 0)));
 BA.debugLineNum = 186;BA.debugLine="lblDescripcion.Top = lblNombre.Height";
Debug.ShouldStop(33554432);
_lbldescripcion.runMethod(true,"setTop",_lblnombre.runMethod(true,"getHeight"));
 BA.debugLineNum = 187;BA.debugLine="lblDescripcion.Left = lblNombre.Left";
Debug.ShouldStop(67108864);
_lbldescripcion.runMethod(true,"setLeft",_lblnombre.runMethod(true,"getLeft"));
 BA.debugLineNum = 188;BA.debugLine="lblDescripcion.Gravity = Gravity.CENTER_VERTICAL";
Debug.ShouldStop(134217728);
_lbldescripcion.runMethod(true,"setGravity",ingresosunicos.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER_VERTICAL"));
 BA.debugLineNum = 189;BA.debugLine="pnlIngresoUnico.AddView(lblDescripcion, lblDescri";
Debug.ShouldStop(268435456);
_pnlingresounico.runVoidMethod ("AddView",(Object)((_lbldescripcion.getObject())),(Object)(_lbldescripcion.runMethod(true,"getLeft")),(Object)(_lbldescripcion.runMethod(true,"getTop")),(Object)(_lbldescripcion.runMethod(true,"getWidth")),(Object)(_lbldescripcion.runMethod(true,"getHeight")));
 BA.debugLineNum = 191;BA.debugLine="lblFecha.Initialize(\"lblFecha\")";
Debug.ShouldStop(1073741824);
_lblfecha.runVoidMethod ("Initialize",ingresosunicos.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("lblFecha")));
 BA.debugLineNum = 192;BA.debugLine="lblFecha.Text = datos.fecha";
Debug.ShouldStop(-2147483648);
_lblfecha.runMethod(true,"setText",BA.ObjectToCharSequence(_datos.getField(true,"fecha" /*RemoteObject*/ )));
 BA.debugLineNum = 193;BA.debugLine="lblFecha.TextSize = 16";
Debug.ShouldStop(1);
_lblfecha.runMethod(true,"setTextSize",BA.numberCast(float.class, 16));
 BA.debugLineNum = 194;BA.debugLine="lblFecha.TextColor = Colors.DarkGray";
Debug.ShouldStop(2);
_lblfecha.runMethod(true,"setTextColor",ingresosunicos.mostCurrent.__c.getField(false,"Colors").getField(true,"DarkGray"));
 BA.debugLineNum = 195;BA.debugLine="lblFecha.Height = pnlIngresoUnico.Height * 0.4";
Debug.ShouldStop(4);
_lblfecha.runMethod(true,"setHeight",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {_pnlingresounico.runMethod(true,"getHeight"),RemoteObject.createImmutable(0.4)}, "*",0, 0)));
 BA.debugLineNum = 196;BA.debugLine="lblFecha.Width = pnlIngresoUnico.Width * 0.9";
Debug.ShouldStop(8);
_lblfecha.runMethod(true,"setWidth",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {_pnlingresounico.runMethod(true,"getWidth"),RemoteObject.createImmutable(0.9)}, "*",0, 0)));
 BA.debugLineNum = 197;BA.debugLine="lblFecha.Top = lblDescripcion.Top + lblDescripcio";
Debug.ShouldStop(16);
_lblfecha.runMethod(true,"setTop",RemoteObject.solve(new RemoteObject[] {_lbldescripcion.runMethod(true,"getTop"),_lbldescripcion.runMethod(true,"getHeight")}, "+",1, 1));
 BA.debugLineNum = 198;BA.debugLine="lblFecha.Left = lblNombre.Left";
Debug.ShouldStop(32);
_lblfecha.runMethod(true,"setLeft",_lblnombre.runMethod(true,"getLeft"));
 BA.debugLineNum = 199;BA.debugLine="lblFecha.Gravity = Gravity.CENTER_VERTICAL";
Debug.ShouldStop(64);
_lblfecha.runMethod(true,"setGravity",ingresosunicos.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER_VERTICAL"));
 BA.debugLineNum = 200;BA.debugLine="pnlIngresoUnico.AddView(lblFecha, lblFecha.Left,";
Debug.ShouldStop(128);
_pnlingresounico.runVoidMethod ("AddView",(Object)((_lblfecha.getObject())),(Object)(_lblfecha.runMethod(true,"getLeft")),(Object)(_lblfecha.runMethod(true,"getTop")),(Object)(_lblfecha.runMethod(true,"getWidth")),(Object)(_lblfecha.runMethod(true,"getHeight")));
 BA.debugLineNum = 202;BA.debugLine="lblMonto.Initialize(\"lblMonto\")";
Debug.ShouldStop(512);
_lblmonto.runVoidMethod ("Initialize",ingresosunicos.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("lblMonto")));
 BA.debugLineNum = 203;BA.debugLine="lblMonto.TextSize = 16";
Debug.ShouldStop(1024);
_lblmonto.runMethod(true,"setTextSize",BA.numberCast(float.class, 16));
 BA.debugLineNum = 204;BA.debugLine="lblMonto.TextColor = Colors.Red";
Debug.ShouldStop(2048);
_lblmonto.runMethod(true,"setTextColor",ingresosunicos.mostCurrent.__c.getField(false,"Colors").getField(true,"Red"));
 BA.debugLineNum = 205;BA.debugLine="lblMonto.Width = cvsTest.MeasureStringWidth((\"$\"";
Debug.ShouldStop(4096);
_lblmonto.runMethod(true,"setWidth",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {ingresosunicos.mostCurrent._cvstest.runMethod(true,"MeasureStringWidth",(Object)((RemoteObject.concat(RemoteObject.createImmutable("$"),_datos.getField(true,"monto" /*RemoteObject*/ )))),(Object)(ingresosunicos.mostCurrent.__c.getField(false,"Typeface").getField(false,"DEFAULT")),(Object)(_lblmonto.runMethod(true,"getTextSize"))),RemoteObject.createImmutable(2)}, "+",1, 0)));
 BA.debugLineNum = 206;BA.debugLine="lblMonto.Height = pnlIngresoUnico.Height * 0.4";
Debug.ShouldStop(8192);
_lblmonto.runMethod(true,"setHeight",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {_pnlingresounico.runMethod(true,"getHeight"),RemoteObject.createImmutable(0.4)}, "*",0, 0)));
 BA.debugLineNum = 207;BA.debugLine="lblMonto.Text = \"$\" & datos.monto";
Debug.ShouldStop(16384);
_lblmonto.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable("$"),_datos.getField(true,"monto" /*RemoteObject*/ ))));
 BA.debugLineNum = 208;BA.debugLine="lblMonto.Top = lblFecha.Top";
Debug.ShouldStop(32768);
_lblmonto.runMethod(true,"setTop",_lblfecha.runMethod(true,"getTop"));
 BA.debugLineNum = 209;BA.debugLine="lblMonto.Left = pnlIngresoUnico.Width - lblMonto.";
Debug.ShouldStop(65536);
_lblmonto.runMethod(true,"setLeft",RemoteObject.solve(new RemoteObject[] {_pnlingresounico.runMethod(true,"getWidth"),_lblmonto.runMethod(true,"getWidth"),_lblnombre.runMethod(true,"getLeft")}, "--",2, 1));
 BA.debugLineNum = 210;BA.debugLine="lblMonto.Gravity = Gravity.CENTER_VERTICAL";
Debug.ShouldStop(131072);
_lblmonto.runMethod(true,"setGravity",ingresosunicos.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER_VERTICAL"));
 BA.debugLineNum = 211;BA.debugLine="pnlIngresoUnico.AddView(lblMonto, lblMonto.Left,";
Debug.ShouldStop(262144);
_pnlingresounico.runVoidMethod ("AddView",(Object)((_lblmonto.getObject())),(Object)(_lblmonto.runMethod(true,"getLeft")),(Object)(_lblmonto.runMethod(true,"getTop")),(Object)(_lblmonto.runMethod(true,"getWidth")),(Object)(_lblmonto.runMethod(true,"getHeight")));
 BA.debugLineNum = 213;BA.debugLine="lblOpciones.Initialize(\"lblOpciones\")";
Debug.ShouldStop(1048576);
_lblopciones.runVoidMethod ("Initialize",ingresosunicos.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("lblOpciones")));
 BA.debugLineNum = 214;BA.debugLine="lblOpciones.Typeface = Typeface.FONTAWESOME";
Debug.ShouldStop(2097152);
_lblopciones.runMethod(false,"setTypeface",ingresosunicos.mostCurrent.__c.getField(false,"Typeface").runMethod(false,"getFONTAWESOME"));
 BA.debugLineNum = 215;BA.debugLine="lblOpciones.Text = Chr(0xF142)";
Debug.ShouldStop(4194304);
_lblopciones.runMethod(true,"setText",BA.ObjectToCharSequence(ingresosunicos.mostCurrent.__c.runMethod(true,"Chr",(Object)(BA.numberCast(int.class, 0xf142)))));
 BA.debugLineNum = 216;BA.debugLine="lblOpciones.TextSize = 18";
Debug.ShouldStop(8388608);
_lblopciones.runMethod(true,"setTextSize",BA.numberCast(float.class, 18));
 BA.debugLineNum = 217;BA.debugLine="lblOpciones.TextColor = Colors.White";
Debug.ShouldStop(16777216);
_lblopciones.runMethod(true,"setTextColor",ingresosunicos.mostCurrent.__c.getField(false,"Colors").getField(true,"White"));
 BA.debugLineNum = 218;BA.debugLine="lblOpciones.Height = lblNombre.Height";
Debug.ShouldStop(33554432);
_lblopciones.runMethod(true,"setHeight",_lblnombre.runMethod(true,"getHeight"));
 BA.debugLineNum = 219;BA.debugLine="lblOpciones.Width = 8dip";
Debug.ShouldStop(67108864);
_lblopciones.runMethod(true,"setWidth",ingresosunicos.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 8))));
 BA.debugLineNum = 220;BA.debugLine="lblOpciones.Left = lblMonto.Left + lblMonto.Width";
Debug.ShouldStop(134217728);
_lblopciones.runMethod(true,"setLeft",RemoteObject.solve(new RemoteObject[] {_lblmonto.runMethod(true,"getLeft"),_lblmonto.runMethod(true,"getWidth"),_lblopciones.runMethod(true,"getWidth")}, "+-",2, 1));
 BA.debugLineNum = 221;BA.debugLine="lblOpciones.Top = 0";
Debug.ShouldStop(268435456);
_lblopciones.runMethod(true,"setTop",BA.numberCast(int.class, 0));
 BA.debugLineNum = 222;BA.debugLine="lblOpciones.Gravity = Gravity.CENTER_VERTICAL";
Debug.ShouldStop(536870912);
_lblopciones.runMethod(true,"setGravity",ingresosunicos.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER_VERTICAL"));
 BA.debugLineNum = 223;BA.debugLine="pnlIngresoUnico.AddView(lblOpciones, lblOpciones.";
Debug.ShouldStop(1073741824);
_pnlingresounico.runVoidMethod ("AddView",(Object)((_lblopciones.getObject())),(Object)(_lblopciones.runMethod(true,"getLeft")),(Object)(_lblopciones.runMethod(true,"getTop")),(Object)(_lblopciones.runMethod(true,"getWidth")),(Object)(_lblopciones.runMethod(true,"getHeight")));
 BA.debugLineNum = 225;BA.debugLine="pnlOpciones.Initialize(\"pnlOpciones\")";
Debug.ShouldStop(1);
_pnlopciones.runVoidMethod ("Initialize",ingresosunicos.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("pnlOpciones")));
 BA.debugLineNum = 226;BA.debugLine="cd.Initialize(Colors.Black, 20)";
Debug.ShouldStop(2);
_cd.runVoidMethod ("Initialize",(Object)(ingresosunicos.mostCurrent.__c.getField(false,"Colors").getField(true,"Black")),(Object)(BA.numberCast(int.class, 20)));
 BA.debugLineNum = 227;BA.debugLine="pnlOpciones.Background = cd";
Debug.ShouldStop(4);
_pnlopciones.runMethod(false,"setBackground",(_cd.getObject()));
 BA.debugLineNum = 228;BA.debugLine="pnlOpciones.Height = pnlIngresoUnico.Height * 0.8";
Debug.ShouldStop(8);
_pnlopciones.runMethod(true,"setHeight",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {_pnlingresounico.runMethod(true,"getHeight"),RemoteObject.createImmutable(0.8)}, "*",0, 0)));
 BA.debugLineNum = 229;BA.debugLine="pnlOpciones.Width = pnlIngresoUnico.Height";
Debug.ShouldStop(16);
_pnlopciones.runMethod(true,"setWidth",_pnlingresounico.runMethod(true,"getHeight"));
 BA.debugLineNum = 230;BA.debugLine="pnlOpciones.Top = lblOpciones.Top";
Debug.ShouldStop(32);
_pnlopciones.runMethod(true,"setTop",_lblopciones.runMethod(true,"getTop"));
 BA.debugLineNum = 231;BA.debugLine="pnlOpciones.Left = lblOpciones.Left - lblOpciones";
Debug.ShouldStop(64);
_pnlopciones.runMethod(true,"setLeft",RemoteObject.solve(new RemoteObject[] {_lblopciones.runMethod(true,"getLeft"),_lblopciones.runMethod(true,"getWidth"),RemoteObject.createImmutable(2),_pnlopciones.runMethod(true,"getWidth")}, "-*-",2, 1));
 BA.debugLineNum = 232;BA.debugLine="pnlOpciones.Visible = False";
Debug.ShouldStop(128);
_pnlopciones.runMethod(true,"setVisible",ingresosunicos.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 233;BA.debugLine="pnlIngresoUnico.AddView(pnlOpciones, pnlOpciones.";
Debug.ShouldStop(256);
_pnlingresounico.runVoidMethod ("AddView",(Object)((_pnlopciones.getObject())),(Object)(_pnlopciones.runMethod(true,"getLeft")),(Object)(_pnlopciones.runMethod(true,"getTop")),(Object)(_pnlopciones.runMethod(true,"getWidth")),(Object)(_pnlopciones.runMethod(true,"getHeight")));
 BA.debugLineNum = 235;BA.debugLine="btnEditar.Initialize(\"btnEditar\")";
Debug.ShouldStop(1024);
_btneditar.runVoidMethod ("Initialize",ingresosunicos.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("btnEditar")));
 BA.debugLineNum = 236;BA.debugLine="btnEditar.Color = Colors.Transparent";
Debug.ShouldStop(2048);
_btneditar.runVoidMethod ("setColor",ingresosunicos.mostCurrent.__c.getField(false,"Colors").getField(true,"Transparent"));
 BA.debugLineNum = 237;BA.debugLine="btnEditar.Text = \"Editar\"";
Debug.ShouldStop(4096);
_btneditar.runMethod(true,"setText",BA.ObjectToCharSequence("Editar"));
 BA.debugLineNum = 238;BA.debugLine="btnEditar.TextColor = Colors.White";
Debug.ShouldStop(8192);
_btneditar.runMethod(true,"setTextColor",ingresosunicos.mostCurrent.__c.getField(false,"Colors").getField(true,"White"));
 BA.debugLineNum = 239;BA.debugLine="btnEditar.TextSize = 14";
Debug.ShouldStop(16384);
_btneditar.runMethod(true,"setTextSize",BA.numberCast(float.class, 14));
 BA.debugLineNum = 240;BA.debugLine="btnEditar.Height = pnlOpciones.Height * 0.4";
Debug.ShouldStop(32768);
_btneditar.runMethod(true,"setHeight",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {_pnlopciones.runMethod(true,"getHeight"),RemoteObject.createImmutable(0.4)}, "*",0, 0)));
 BA.debugLineNum = 241;BA.debugLine="btnEditar.Width = pnlOpciones.Height * 0.8";
Debug.ShouldStop(65536);
_btneditar.runMethod(true,"setWidth",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {_pnlopciones.runMethod(true,"getHeight"),RemoteObject.createImmutable(0.8)}, "*",0, 0)));
 BA.debugLineNum = 242;BA.debugLine="btnEditar.Top = (pnlOpciones.Height * 0.2) / 3";
Debug.ShouldStop(131072);
_btneditar.runMethod(true,"setTop",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {(RemoteObject.solve(new RemoteObject[] {_pnlopciones.runMethod(true,"getHeight"),RemoteObject.createImmutable(0.2)}, "*",0, 0)),RemoteObject.createImmutable(3)}, "/",0, 0)));
 BA.debugLineNum = 243;BA.debugLine="btnEditar.Left = (pnlOpciones.Width - btnEditar.W";
Debug.ShouldStop(262144);
_btneditar.runMethod(true,"setLeft",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {(RemoteObject.solve(new RemoteObject[] {_pnlopciones.runMethod(true,"getWidth"),_btneditar.runMethod(true,"getWidth")}, "-",1, 1)),RemoteObject.createImmutable(2)}, "/",0, 0)));
 BA.debugLineNum = 244;BA.debugLine="pnlOpciones.AddView(btnEditar, btnEditar.Left, bt";
Debug.ShouldStop(524288);
_pnlopciones.runVoidMethod ("AddView",(Object)((_btneditar.getObject())),(Object)(_btneditar.runMethod(true,"getLeft")),(Object)(_btneditar.runMethod(true,"getTop")),(Object)(_btneditar.runMethod(true,"getWidth")),(Object)(_btneditar.runMethod(true,"getHeight")));
 BA.debugLineNum = 246;BA.debugLine="btnEliminar.Initialize(\"btnEliminar\")";
Debug.ShouldStop(2097152);
_btneliminar.runVoidMethod ("Initialize",ingresosunicos.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("btnEliminar")));
 BA.debugLineNum = 247;BA.debugLine="btnEliminar.Color = Colors.Transparent";
Debug.ShouldStop(4194304);
_btneliminar.runVoidMethod ("setColor",ingresosunicos.mostCurrent.__c.getField(false,"Colors").getField(true,"Transparent"));
 BA.debugLineNum = 248;BA.debugLine="btnEliminar.Text = \"Eliminar\"";
Debug.ShouldStop(8388608);
_btneliminar.runMethod(true,"setText",BA.ObjectToCharSequence("Eliminar"));
 BA.debugLineNum = 249;BA.debugLine="btnEliminar.TextColor = Colors.White";
Debug.ShouldStop(16777216);
_btneliminar.runMethod(true,"setTextColor",ingresosunicos.mostCurrent.__c.getField(false,"Colors").getField(true,"White"));
 BA.debugLineNum = 250;BA.debugLine="btnEliminar.TextSize = 14";
Debug.ShouldStop(33554432);
_btneliminar.runMethod(true,"setTextSize",BA.numberCast(float.class, 14));
 BA.debugLineNum = 251;BA.debugLine="btnEliminar.Height = btnEditar.Height";
Debug.ShouldStop(67108864);
_btneliminar.runMethod(true,"setHeight",_btneditar.runMethod(true,"getHeight"));
 BA.debugLineNum = 252;BA.debugLine="btnEliminar.Width = pnlOpciones.Width * 0.9";
Debug.ShouldStop(134217728);
_btneliminar.runMethod(true,"setWidth",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {_pnlopciones.runMethod(true,"getWidth"),RemoteObject.createImmutable(0.9)}, "*",0, 0)));
 BA.debugLineNum = 253;BA.debugLine="btnEliminar.Top = btnEditar.Top * 2 + btnEditar.H";
Debug.ShouldStop(268435456);
_btneliminar.runMethod(true,"setTop",RemoteObject.solve(new RemoteObject[] {_btneditar.runMethod(true,"getTop"),RemoteObject.createImmutable(2),_btneditar.runMethod(true,"getHeight")}, "*+",1, 1));
 BA.debugLineNum = 254;BA.debugLine="btnEliminar.Left = (pnlOpciones.Width - btnElimin";
Debug.ShouldStop(536870912);
_btneliminar.runMethod(true,"setLeft",BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {(RemoteObject.solve(new RemoteObject[] {_pnlopciones.runMethod(true,"getWidth"),_btneliminar.runMethod(true,"getWidth")}, "-",1, 1)),RemoteObject.createImmutable(2)}, "/",0, 0)));
 BA.debugLineNum = 255;BA.debugLine="pnlOpciones.AddView(btnEliminar, btnEliminar.Left";
Debug.ShouldStop(1073741824);
_pnlopciones.runVoidMethod ("AddView",(Object)((_btneliminar.getObject())),(Object)(_btneliminar.runMethod(true,"getLeft")),(Object)(_btneliminar.runMethod(true,"getTop")),(Object)(_btneliminar.runMethod(true,"getWidth")),(Object)(_btneliminar.runMethod(true,"getHeight")));
 BA.debugLineNum = 257;BA.debugLine="pnlDeslizable.AddView(pnlIngresoUnico, pnlIngreso";
Debug.ShouldStop(1);
ingresosunicos.mostCurrent._pnldeslizable.runVoidMethod ("AddView",(Object)((_pnlingresounico.getObject())),(Object)(_pnlingresounico.runMethod(true,"getLeft")),(Object)(_top),(Object)(_pnlingresounico.runMethod(true,"getWidth")),(Object)(_pnlingresounico.runMethod(true,"getHeight")));
 BA.debugLineNum = 261;BA.debugLine="Dim referencia As IndiceIngresoUnico";
Debug.ShouldStop(16);
_referencia = RemoteObject.createNew ("pullup.wallet.ingresosunicos._indiceingresounico");Debug.locals.put("referencia", _referencia);
 BA.debugLineNum = 262;BA.debugLine="referencia.indiceElemento = indice";
Debug.ShouldStop(32);
_referencia.setField ("indiceElemento" /*RemoteObject*/ ,_indice);
 BA.debugLineNum = 263;BA.debugLine="referencia.rowid = 0";
Debug.ShouldStop(64);
_referencia.setField ("rowid" /*RemoteObject*/ ,BA.numberCast(int.class, 0));
 BA.debugLineNum = 265;BA.debugLine="lblOpciones.Tag = referencia";
Debug.ShouldStop(256);
_lblopciones.runMethod(false,"setTag",(_referencia));
 BA.debugLineNum = 268;BA.debugLine="Dim referencia2 As IndiceIngresoUnico";
Debug.ShouldStop(2048);
_referencia2 = RemoteObject.createNew ("pullup.wallet.ingresosunicos._indiceingresounico");Debug.locals.put("referencia2", _referencia2);
 BA.debugLineNum = 269;BA.debugLine="referencia2.indiceElemento = 0";
Debug.ShouldStop(4096);
_referencia2.setField ("indiceElemento" /*RemoteObject*/ ,BA.numberCast(int.class, 0));
 BA.debugLineNum = 270;BA.debugLine="referencia2.rowid = datos.rowid";
Debug.ShouldStop(8192);
_referencia2.setField ("rowid" /*RemoteObject*/ ,_datos.getField(true,"rowid" /*RemoteObject*/ ));
 BA.debugLineNum = 272;BA.debugLine="pnlOpciones.Tag = referencia2";
Debug.ShouldStop(32768);
_pnlopciones.runMethod(false,"setTag",(_referencia2));
 BA.debugLineNum = 275;BA.debugLine="Relaciones(indice, 0) = lblOpciones";
Debug.ShouldStop(262144);
ingresosunicos.mostCurrent._relaciones.setArrayElement (RemoteObject.declareNull("anywheresoftware.b4a.AbsObjectWrapper").runMethod(false, "ConvertToWrapper", RemoteObject.createNew("anywheresoftware.b4a.objects.B4XViewWrapper"), _lblopciones.getObject()),_indice,BA.numberCast(int.class, 0));
 BA.debugLineNum = 276;BA.debugLine="Relaciones(indice, 1) = pnlOpciones";
Debug.ShouldStop(524288);
ingresosunicos.mostCurrent._relaciones.setArrayElement (RemoteObject.declareNull("anywheresoftware.b4a.AbsObjectWrapper").runMethod(false, "ConvertToWrapper", RemoteObject.createNew("anywheresoftware.b4a.objects.B4XViewWrapper"), _pnlopciones.getObject()),_indice,BA.numberCast(int.class, 1));
 BA.debugLineNum = 279;BA.debugLine="arrayPnlsOpciones(indice) = pnlOpciones";
Debug.ShouldStop(4194304);
ingresosunicos.mostCurrent._arraypnlsopciones.setArrayElement (RemoteObject.declareNull("anywheresoftware.b4a.AbsObjectWrapper").runMethod(false, "ConvertToWrapper", RemoteObject.createNew("anywheresoftware.b4a.objects.B4XViewWrapper"), _pnlopciones.getObject()),_indice);
 BA.debugLineNum = 280;BA.debugLine="End Sub";
Debug.ShouldStop(8388608);
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _globals() throws Exception{
 //BA.debugLineNum = 12;BA.debugLine="Sub Globals";
 //BA.debugLineNum = 15;BA.debugLine="Type IndiceIngresoUnico(indiceElemento As Int, ro";
;
 //BA.debugLineNum = 16;BA.debugLine="Type IngresoUnico(rowid As Int, nombre As String,";
;
 //BA.debugLineNum = 17;BA.debugLine="Dim alturaDispositivo As Int";
ingresosunicos._alturadispositivo = RemoteObject.createImmutable(0);
 //BA.debugLineNum = 18;BA.debugLine="Dim anchoDispositivo As Int";
ingresosunicos._anchodispositivo = RemoteObject.createImmutable(0);
 //BA.debugLineNum = 19;BA.debugLine="Dim nRegistros As Int";
ingresosunicos._nregistros = RemoteObject.createImmutable(0);
 //BA.debugLineNum = 20;BA.debugLine="Dim Relaciones(,) As B4XView";
ingresosunicos.mostCurrent._relaciones = RemoteObject.createNewArray ("anywheresoftware.b4a.objects.B4XViewWrapper", new int[] {0,0}, new Object[]{});
 //BA.debugLineNum = 21;BA.debugLine="Dim arrayPnlsOpciones() As B4XView";
ingresosunicos.mostCurrent._arraypnlsopciones = RemoteObject.createNewArray ("anywheresoftware.b4a.objects.B4XViewWrapper", new int[] {0}, new Object[]{});
 //BA.debugLineNum = 22;BA.debugLine="Private btnMenu As Button";
ingresosunicos.mostCurrent._btnmenu = RemoteObject.createNew ("anywheresoftware.b4a.objects.ButtonWrapper");
 //BA.debugLineNum = 23;BA.debugLine="Private lblContornoBoton As Label";
ingresosunicos.mostCurrent._lblcontornoboton = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
 //BA.debugLineNum = 24;BA.debugLine="Private pnlNavInferior As Panel";
ingresosunicos.mostCurrent._pnlnavinferior = RemoteObject.createNew ("anywheresoftware.b4a.objects.PanelWrapper");
 //BA.debugLineNum = 25;BA.debugLine="Private pnlDeslizable As Panel";
ingresosunicos.mostCurrent._pnldeslizable = RemoteObject.createNew ("anywheresoftware.b4a.objects.PanelWrapper");
 //BA.debugLineNum = 26;BA.debugLine="Private svPantalla As ScrollView";
ingresosunicos.mostCurrent._svpantalla = RemoteObject.createNew ("anywheresoftware.b4a.objects.ScrollViewWrapper");
 //BA.debugLineNum = 27;BA.debugLine="Dim cur As Cursor";
ingresosunicos.mostCurrent._cur = RemoteObject.createNew ("anywheresoftware.b4a.sql.SQL.CursorWrapper");
 //BA.debugLineNum = 28;BA.debugLine="Dim cs As CSBuilder";
ingresosunicos.mostCurrent._cs = RemoteObject.createNew ("anywheresoftware.b4a.objects.CSBuilder");
 //BA.debugLineNum = 29;BA.debugLine="Dim cvsTest As Canvas";
ingresosunicos.mostCurrent._cvstest = RemoteObject.createNew ("anywheresoftware.b4a.objects.drawable.CanvasWrapper");
 //BA.debugLineNum = 30;BA.debugLine="Dim bmpTest As Bitmap";
ingresosunicos.mostCurrent._bmptest = RemoteObject.createNew ("anywheresoftware.b4a.objects.drawable.CanvasWrapper.BitmapWrapper");
 //BA.debugLineNum = 31;BA.debugLine="Dim sumaIngresosAntigua As Int";
ingresosunicos._sumaingresosantigua = RemoteObject.createImmutable(0);
 //BA.debugLineNum = 32;BA.debugLine="Dim montoSeleccionado As Int";
ingresosunicos._montoseleccionado = RemoteObject.createImmutable(0);
 //BA.debugLineNum = 33;BA.debugLine="Dim sumaIngresosActual As Int";
ingresosunicos._sumaingresosactual = RemoteObject.createImmutable(0);
 //BA.debugLineNum = 34;BA.debugLine="End Sub";
return RemoteObject.createImmutable("");
}
public static RemoteObject  _lblopciones_click() throws Exception{
try {
		Debug.PushSubsStack("lblOpciones_Click (ingresosunicos) ","ingresosunicos",12,ingresosunicos.mostCurrent.activityBA,ingresosunicos.mostCurrent,283);
if (RapidSub.canDelegate("lblopciones_click")) { return pullup.wallet.ingresosunicos.remoteMe.runUserSub(false, "ingresosunicos","lblopciones_click");}
RemoteObject _lblopcion = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _indice = RemoteObject.declareNull("pullup.wallet.ingresosunicos._indiceingresounico");
int _contador = 0;
 BA.debugLineNum = 283;BA.debugLine="Sub lblOpciones_Click";
Debug.ShouldStop(67108864);
 BA.debugLineNum = 284;BA.debugLine="Dim lblOpcion As Label";
Debug.ShouldStop(134217728);
_lblopcion = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("lblOpcion", _lblopcion);
 BA.debugLineNum = 285;BA.debugLine="Dim indice As IndiceIngresoUnico";
Debug.ShouldStop(268435456);
_indice = RemoteObject.createNew ("pullup.wallet.ingresosunicos._indiceingresounico");Debug.locals.put("indice", _indice);
 BA.debugLineNum = 287;BA.debugLine="lblOpcion = Sender";
Debug.ShouldStop(1073741824);
_lblopcion = RemoteObject.declareNull("anywheresoftware.b4a.AbsObjectWrapper").runMethod(false, "ConvertToWrapper", RemoteObject.createNew("anywheresoftware.b4a.objects.LabelWrapper"), ingresosunicos.mostCurrent.__c.runMethod(false,"Sender",ingresosunicos.mostCurrent.activityBA));
 BA.debugLineNum = 288;BA.debugLine="indice = lblOpcion.Tag";
Debug.ShouldStop(-2147483648);
_indice = (_lblopcion.runMethod(false,"getTag"));Debug.locals.put("indice", _indice);
 BA.debugLineNum = 291;BA.debugLine="For contador = 0 To arrayPnlsOpciones.Length - 1";
Debug.ShouldStop(4);
{
final int step5 = 1;
final int limit5 = RemoteObject.solve(new RemoteObject[] {ingresosunicos.mostCurrent._arraypnlsopciones.getField(true,"length"),RemoteObject.createImmutable(1)}, "-",1, 1).<Integer>get().intValue();
_contador = 0 ;
for (;(step5 > 0 && _contador <= limit5) || (step5 < 0 && _contador >= limit5) ;_contador = ((int)(0 + _contador + step5))  ) {
Debug.locals.put("contador", _contador);
 BA.debugLineNum = 292;BA.debugLine="If (contador <> indice.indiceElemento) Then";
Debug.ShouldStop(8);
if ((RemoteObject.solveBoolean("!",RemoteObject.createImmutable(_contador),BA.numberCast(double.class, _indice.getField(true,"indiceElemento" /*RemoteObject*/ ))))) { 
 BA.debugLineNum = 293;BA.debugLine="arrayPnlsOpciones(contador).Visible = False";
Debug.ShouldStop(16);
ingresosunicos.mostCurrent._arraypnlsopciones.getArrayElement(false,BA.numberCast(int.class, _contador)).runMethod(true,"setVisible",ingresosunicos.mostCurrent.__c.getField(true,"False"));
 };
 }
}Debug.locals.put("contador", _contador);
;
 BA.debugLineNum = 298;BA.debugLine="Relaciones(indice.indiceElemento, 1).SetVisibleAn";
Debug.ShouldStop(512);
ingresosunicos.mostCurrent._relaciones.getArrayElement(false,_indice.getField(true,"indiceElemento" /*RemoteObject*/ ),BA.numberCast(int.class, 1)).runVoidMethod ("SetVisibleAnimated",(Object)(BA.numberCast(int.class, 200)),(Object)(ingresosunicos.mostCurrent.__c.runMethod(true,"Not",(Object)(ingresosunicos.mostCurrent._relaciones.getArrayElement(false,_indice.getField(true,"indiceElemento" /*RemoteObject*/ ),BA.numberCast(int.class, 1)).runMethod(true,"getVisible")))));
 BA.debugLineNum = 299;BA.debugLine="End Sub";
Debug.ShouldStop(1024);
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _process_globals() throws Exception{
 //BA.debugLineNum = 6;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 9;BA.debugLine="Dim sql As SQL";
ingresosunicos._sql = RemoteObject.createNew ("anywheresoftware.b4a.sql.SQL");
 //BA.debugLineNum = 10;BA.debugLine="End Sub";
return RemoteObject.createImmutable("");
}
}